In [1]:
import pandas as pd
import numpy as np

## Сначала получим точки всех станций

- читаю файл bike_share/daily_rent_detail.csv

In [2]:
daily_rent_detail = pd.read_csv('../../bike_share/daily_rent_detail.csv')
daily_rent_detail

C:\Users\lenov\AppData\Local\Temp\ipykernel_6900\2254643125.py:1: DtypeWarning: Columns (0: start_station_id, 1: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  daily_rent_detail = pd.read_csv('../../bike_share/daily_rent_detail.csv')

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,946D42AD89539210,docked_bike,2020-05-30 17:25:29,2020-05-31 18:25:22,Anacostia Library,31804,11th & H St NE,31614.0,38.865784,-76.978400,38.899983,-76.991383,casual
1,CC46FAAB662B8613,docked_bike,2020-05-09 14:42:04,2020-05-09 15:06:33,10th & E St NW,31256,21st St & Constitution Ave NW,31261.0,38.895914,-77.026064,38.892459,-77.046567,member
2,72F00B2FB833D6ED,docked_bike,2020-05-24 17:27:19,2020-05-24 17:43:51,Connecticut Ave & Newark St NW / Cleveland Park,31305,12th & U St NW,31268.0,38.934267,-77.057979,38.916787,-77.028139,member
3,4DFBE6AED989DF35,docked_bike,2020-05-27 15:29:52,2020-05-27 15:47:13,Connecticut Ave & Newark St NW / Cleveland Park,31305,14th & Belmont St NW,31119.0,38.934267,-77.057979,38.921074,-77.031887,casual
4,1AAFE6B4331AB9DF,docked_bike,2020-05-31 14:06:03,2020-05-31 14:30:30,Georgia Ave & Morton St NW,31419,17th & K St NW,31213.0,38.932128,-77.023500,38.902760,-77.038630,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16086667,117C27DBDD138B72,electric_bike,2024-08-01 08:10:22.293,2024-08-01 08:10:37.641,NaN,NaN,NaN,NaN,38.890000,-77.000000,38.890000,-77.000000,member
16086668,4774F4D630258482,electric_bike,2024-08-08 10:05:21.938,2024-08-08 10:21:46.654,NaN,NaN,NaN,NaN,38.900000,-77.000000,38.870000,-76.950000,member
16086669,D75836E25E77B5EC,electric_bike,2024-08-03 16:29:32.252,2024-08-03 16:35:43.179,NaN,NaN,NaN,NaN,38.920000,-76.990000,38.920000,-77.000000,member
16086670,3B888603D18116DC,electric_bike,2024-08-03 02:49:45.661,2024-08-03 02:59:56.877,NaN,NaN,NaN,NaN,38.920000,-77.020000,38.920000,-77.030000,member
16086671,3B201BA37CE6ED10,electric_bike,2024-08-15 07:51:42.628,2024-08-15 07:55:50.645,NaN,NaN,NaN,NaN,38.940000,-77.030000,38.930000,-77.030000,member

- убирал станцию 'MTL-ECO5-03' так как она занимает 2 строчки во всем dataframe

In [3]:
daily_rent_detail = daily_rent_detail[daily_rent_detail['start_station_id'] != 'MTL-ECO5-03']

- заменил в столбце start_station_id Nan на 0

In [4]:
daily_rent_detail['start_station_id'] = daily_rent_detail['start_station_id'].replace(np.nan, 0)

- заменил в столбце end_station_id Nan на 0

In [5]:
daily_rent_detail['end_station_id'] = daily_rent_detail['end_station_id'].replace(np.nan, 0)

- посмотрел результат

In [6]:
daily_rent_detail

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,946D42AD89539210,docked_bike,2020-05-30 17:25:29,2020-05-31 18:25:22,Anacostia Library,31804,11th & H St NE,31614.0,38.865784,-76.978400,38.899983,-76.991383,casual
1,CC46FAAB662B8613,docked_bike,2020-05-09 14:42:04,2020-05-09 15:06:33,10th & E St NW,31256,21st St & Constitution Ave NW,31261.0,38.895914,-77.026064,38.892459,-77.046567,member
2,72F00B2FB833D6ED,docked_bike,2020-05-24 17:27:19,2020-05-24 17:43:51,Connecticut Ave & Newark St NW / Cleveland Park,31305,12th & U St NW,31268.0,38.934267,-77.057979,38.916787,-77.028139,member
3,4DFBE6AED989DF35,docked_bike,2020-05-27 15:29:52,2020-05-27 15:47:13,Connecticut Ave & Newark St NW / Cleveland Park,31305,14th & Belmont St NW,31119.0,38.934267,-77.057979,38.921074,-77.031887,casual
4,1AAFE6B4331AB9DF,docked_bike,2020-05-31 14:06:03,2020-05-31 14:30:30,Georgia Ave & Morton St NW,31419,17th & K St NW,31213.0,38.932128,-77.023500,38.902760,-77.038630,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16086667,117C27DBDD138B72,electric_bike,2024-08-01 08:10:22.293,2024-08-01 08:10:37.641,NaN,0,NaN,0,38.890000,-77.000000,38.890000,-77.000000,member
16086668,4774F4D630258482,electric_bike,2024-08-08 10:05:21.938,2024-08-08 10:21:46.654,NaN,0,NaN,0,38.900000,-77.000000,38.870000,-76.950000,member
16086669,D75836E25E77B5EC,electric_bike,2024-08-03 16:29:32.252,2024-08-03 16:35:43.179,NaN,0,NaN,0,38.920000,-76.990000,38.920000,-77.000000,member
16086670,3B888603D18116DC,electric_bike,2024-08-03 02:49:45.661,2024-08-03 02:59:56.877,NaN,0,NaN,0,38.920000,-77.020000,38.920000,-77.030000,member
16086671,3B201BA37CE6ED10,electric_bike,2024-08-15 07:51:42.628,2024-08-15 07:55:50.645,NaN,0,NaN,0,38.940000,-77.030000,38.930000,-77.030000,member

- оставляю только те станции, которые не равны 0

In [7]:
daily_rent_detail = daily_rent_detail[(daily_rent_detail['start_station_id'] != 0) & (daily_rent_detail['end_station_id'] != 0)]

- меняю типы данных у столбцов (start_station_id, end_station_id) на float32

In [8]:
daily_rent_detail = daily_rent_detail.astype(
    {
        'start_station_id': 'float32',
        'end_station_id': 'float32'
    }
)

- затем меняю типы данных (start_station_id, end_station_id) на int32 так как станции были и сплавающей точкой и целым числом

In [9]:
daily_rent_detail = daily_rent_detail.astype(
    {
        'start_station_id': 'int32',
        'end_station_id': 'int32'
    }
)

- смотрю что получилось

In [10]:
daily_rent_detail.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,946D42AD89539210,docked_bike,2020-05-30 17:25:29,2020-05-31 18:25:22,Anacostia Library,31804,11th & H St NE,31614,38.865784,-76.978400,38.899983,-76.991383,casual
1,CC46FAAB662B8613,docked_bike,2020-05-09 14:42:04,2020-05-09 15:06:33,10th & E St NW,31256,21st St & Constitution Ave NW,31261,38.895914,-77.026064,38.892459,-77.046567,member
2,72F00B2FB833D6ED,docked_bike,2020-05-24 17:27:19,2020-05-24 17:43:51,Connecticut Ave & Newark St NW / Cleveland Park,31305,12th & U St NW,31268,38.934267,-77.057979,38.916787,-77.028139,member
3,4DFBE6AED989DF35,docked_bike,2020-05-27 15:29:52,2020-05-27 15:47:13,Connecticut Ave & Newark St NW / Cleveland Park,31305,14th & Belmont St NW,31119,38.934267,-77.057979,38.921074,-77.031887,casual
4,1AAFE6B4331AB9DF,docked_bike,2020-05-31 14:06:03,2020-05-31 14:30:30,Georgia Ave & Morton St NW,31419,17th & K St NW,31213,38.932128,-77.023500,38.902760,-77.038630,casual

- написал код который получит для каждой станции медианное значение точки, где расположенна станция

In [ ]:
station_dict = {
    int(k): [float(v[0]), float(v[1])]
    for k, v in (
        daily_rent_detail
        .groupby('start_station_id')[['start_lat', 'start_lng']]
        .median()
        .apply(lambda row: [round(row['start_lat'], 6), round(row['start_lng'], 6)], axis=1)
        .to_dict()
        .items()
    )
}
station_dict

{30200: [38.89428, -77.023979],
 30201: [38.898097, -77.023924],
 31000: [38.858971, -77.05323],
 31001: [38.85725, -77.05332],
 31002: [38.856425, -77.049232],
 31003: [38.861056, -77.049417],
 31004: [38.857866, -77.05949],
 31005: [38.862303, -77.059936],
 31006: [38.863314, -77.063416],
 31007: [38.857785, -77.051698],
 31009: [38.848466, -77.051514],
 31010: [38.8426, -77.0502],
 31011: [38.852929, -77.049723],
 31012: [38.850688, -77.05152],
 31013: [38.854381, -77.053412],
 31014: [38.897315, -77.070993],
 31015: [38.8946, -77.072305],
 31016: [38.893438, -77.076389],
 31017: [38.891696, -77.0846],
 31018: [38.892164, -77.079375],
 31019: [38.889396, -77.091862],
 31020: [38.8904, -77.0889],
 31021: [38.8881, -77.09308],
 31022: [38.88701, -77.095257],
 31023: [38.885801, -77.097745],
 31024: [38.882788, -77.103148],
 31025: [38.88397, -77.10783],
 31026: [38.884734, -77.093485],
 31027: [38.893993, -77.07857],
 31028: [38.893237, -77.086063],
 31029: [38.896923, -77.086502],
 31030: [38.89593, -77.089006],
 31031: [38.89054, -77.08095],
 31032: [38.88081, -77.090792],
 31033: [38.850337, -77.100989],
 31034: [38.882629, -77.109366],
 31035: [38.876393, -77.107735],
 31036: [38.87887, -77.1207],
 31037: [38.881044, -77.111768],
 31038: [38.883921, -77.116817],
 31039: [38.880012, -77.107854],
 31040: [38.884703, -77.100302],
 31041: [38.803124, -77.040363],
 31042: [38.804718, -77.043363],
 31043: [38.810741, -77.044633],
 31044: [38.805317, -77.049883],
 31045: [38.805648, -77.05293],
 31046: [38.811456, -77.050276],
 31047: [38.814577, -77.052808],
 31048: [38.805763, -77.060627],
 31049: [38.882425, -77.112754],
 31050: [38.884961, -77.08777],
 31051: [38.889365, -77.077294],
 31052: [38.844015, -77.050537],
 31053: [38.863833, -77.080319],
 31054: [38.847129, -77.11255],
 31055: [38.846222, -77.069275],
 31056: [38.847977, -77.075104],
 31057: [38.8444, -77.085931],
 31058: [38.860344, -77.093672],
 31059: [38.84736, -77.095431],
 31060: [38.84232, -77.089555],
 31061: [38.848454, -77.084918],
 31062: [38.896553, -77.06714],
 31063: [38.852248, -77.105022],
 31064: [38.865029, -77.039511],
 31065: [38.880705, -77.08596],
 31066: [38.867262, -77.072315],
 31067: [38.862478, -77.086599],
 31068: [38.856319, -77.11153],
 31069: [38.871822, -77.107906],
 31070: [38.873755, -77.089233],
 31071: [38.862753, -77.05428],
 31072: [38.837846, -77.093478],
 31073: [38.873219, -77.082104],
 31074: [38.869418, -77.095596],
 31075: [38.866471, -77.076131],
 31076: [38.840654, -77.088659],
 31077: [38.88992, -77.071301],
 31078: [38.869442, -77.104503],
 31079: [38.894941, -77.09169],
 31080: [38.897612, -77.080851],
 31081: [38.804378, -77.060866],
 31082: [38.801111, -77.068952],
 31083: [38.82175, -77.047494],
 31084: [38.802677, -77.063562],
 31085: [38.820064, -77.057619],
 31086: [38.82595, -77.058541],
 31087: [38.820932, -77.053096],
 31088: [38.833077, -77.059821],
 31089: [38.890612, -77.084801],
 31090: [38.865553, -77.05003],
 31091: [38.859254, -77.063275],
 31092: [38.896456, -77.104562],
 31093: [38.898984, -77.078317],
 31094: [38.895377, -77.09713],
 31095: [38.86215, -77.068121],
 31096: [38.86612, -77.08787],
 31097: [38.812718, -77.044097],
 31098: [38.80704, -77.059817],
 31099: [38.813485, -77.049468],
 31100: [38.9003, -77.0429],
 31101: [38.917764, -77.032096],
 31102: [38.929464, -77.027822],
 31103: [38.926088, -77.036536],
 31104: [38.922923, -77.042525],
 31105: [38.9268, -77.0322],
 31106: [38.923203, -77.047637],
 31107: [38.9319, -77.0388],
 31108: [38.876697, -77.017897],
 31109: [38.915658, -77.0222],
 31110: [38.9154, -77.0446],
 31111: [38.9172, -77.0259],
 31112: [38.927872, -77.043358],
 31113: [38.920669, -77.04368],
 31114: [38.918809, -77.041571],
 31115: [38.928121, -77.023795],
 31116: [38.917761, -77.04062],
 31117: [38.92333, -77.0352],
 31118: [38.917622, -77.01597],
 31119: [38.921074, -77.031887],
 31120: [38.920387, -77.025672],
 31121: [38.923583, -77.050046],
 31122: [38.928893, -77.03625],
 31123: [38.925284, -77.032375],
 31124: [38.928552, -77.032224],
 31125: [38.919018, -77.034449],
 31126: [38.925636, -77.027112],
 31127: [38.898925, -77.048852],
 31128: [38.905303, -77.050264],
 31129: [38.896465, -77.033381],
 31130: [38.914174, -77.021595],
 31131: [38.934405, -77.032687],
 31132: [38.916936, -77.029631],
 31133: [38.918036, -77.045487],
 31134: [38.917716, -77.022684],
 31135: [38.926102, -77.03665],
 31136: [38.922324, -77.027086],
 31137: [38.937135, -77.019125],
 31138: [38.921233, -77.018135],
 31200: [38.9101, -77.0444],
 31201: [38.909801, -77.034427],
 31202: [38.913046, -77.032008],
 31203: [38.9086, -77.0323],
 31204: [38.8963, -77.045],
 31205: [38.900711, -77.046449],
 31206: [38.8952, -77.0436],
 31207: [38.924822, -77.022264],
 31208: [38.8763, -77.0037],
 31209: [38.874954, -77.005754],
 31210: [38.906767, -77.038627],
 31211: [38.897293, -77.05557],
 31212: [38.905711, -77.047318],
 31213: [38.90276, -77.03863],
 31214: [38.9121, -77.0387],
 31215: [38.902314, -77.059142],
 31216: [38.899632, -77.031686],
 31217: [38.886277, -77.028242],
 31218: [38.886266, -77.022241],
 31219: [38.893028, -77.026013],
 31220: [38.894919, -77.046587],
 31221: [38.905067, -77.041779],
 31222: [38.899032, -77.033354],
 31223: [38.905737, -77.02227],
 31224: [38.903741, -77.042452],
 31225: [38.90375, -77.06269],
 31226: [38.916442, -77.0682],
 31227: [38.900283, -77.029822],
 31228: [38.8997, -77.023086],
 31229: [38.915544, -77.038252],
 31230: [38.898326, -77.027959],
 31231: [38.894514, -77.031617],
 31232: [38.897283, -77.022191],
 31233: [38.902061, -77.038322],
 31234: [38.908905, -77.04478],
 31235: [38.8923, -77.0436],
 31236: [38.907796, -77.071652],
 31237: [38.903827, -77.053485],
 31238: [38.898164, -77.031898],
 31239: [38.905996, -77.039802],
 31240: [38.88412, -77.04657],
 31241: [38.9059, -77.0325],
 31242: [38.89968, -77.041539],
 31243: [38.886372, -77.017701],
 31244: [38.88412, -77.017445],
 31245: [38.912719, -77.022155],
 31246: [38.905126, -77.056887],
 31247: [38.888552, -77.032427],
 31248: [38.888774, -77.028694],
 31249: [38.879819, -77.037413],
 31250: [38.903584, -77.044789],
 31251: [38.903819, -77.0284],
 31252: [38.901539, -77.046564],
 31253: [38.9019, -77.043386],
 31254: [38.902, -77.03353],
 31255: [38.9066, -77.05152],
 31256: [38.895914, -77.026064],
 31257: [38.90088, -77.048911],
 31258: [38.888255, -77.049436],
 31259: [38.894722, -77.045128],
 31260: [38.896104, -77.049882],
 31261: [38.892459, -77.046567],
 31262: [38.897857, -77.026975],
 31263: [38.9024, -77.02622],
 31264: [38.894573, -77.01994],
 31265: [38.90093, -77.018677],
 31266: [38.905578, -77.027313],
 31267: [38.908142, -77.038359],
 31268: [38.916787, -77.028139],
 31269: [38.887378, -77.001955],
 31270: [38.894851, -77.02324],
 31271: [38.892275, -77.013917],
 31272: [38.886978, -77.013769],
 31273: [38.878433, -77.03023],
 31274: [38.898243, -77.026235],
 31275: [38.901755, -77.051084],
 31276: [38.903649, -77.034918],
 31277: [38.898301, -77.039732],
 31278: [38.912648, -77.041834],
 31279: [38.898412, -77.043182],
 31280: [38.913761, -77.027025],
 31281: [38.90864, -77.02277],
 31282: [38.912652, -77.036278],
 31283: [38.903658, -77.031737],
 31284: [38.893511, -77.041544],
 31285: [38.909394, -77.048728],
 31286: [38.90843, -77.02714],
 31287: [38.884323, -77.02601],
 31288: [38.890496, -77.017246],
 31289: [38.890539, -77.049383],
 31290: [38.888097, -77.038325],
 31291: [38.901136, -77.034451],
 31292: [38.892441, -77.048947],
 31293: [38.902826, -77.060173],
 31294: [38.88345, -77.021741],
 31295: [38.905509, -77.065246],
 31296: [38.924088, -77.040787],
 31297: [38.89846, -77.053052],
 31298: [38.905424, -77.034674],
 31299: [38.912644, -77.04564],
 31300: [38.944551, -77.063896],
 31301: [38.938736, -77.087171],
 31302: [38.934881, -77.072755],
 31303: [38.947607, -77.079382],
 31304: [38.922581, -77.070334],
 31305: [38.933679, -77.057588],
 31306: [38.922649, -77.077271],
 31307: [38.930282, -77.055599],
 31308: [38.943837, -77.077078],
 31309: [38.954812, -77.082426],
 31310: [38.955016, -77.069956],
 31311: [38.908735, -77.029779],
 31312: [38.90849, -77.063586],
 31313: [38.941139, -77.061977],
 31314: [38.903732, -77.067528],
 31315: [38.964544, -77.075135],
 31316: [38.946182, -77.08059],
 31317: [38.958267, -77.084636],
 31318: [38.947156, -77.065115],
 31319: [38.949813, -77.080217],
 31320: [38.936298, -77.087128],
 31321: [38.892244, -77.033234],
 31322: [38.917036, -77.095782],
 31323: [38.923389, -77.051833],
 31324: [38.911268, -77.041829],
 31325: [38.912614, -77.074323],
 31326: [38.909701, -77.085646],
 31327: [38.910674, -77.03188],
 31328: [38.898302, -77.046913],
 31329: [38.895509, -77.037925],
 31330: [38.909858, -77.038566],
 31331: [38.927294, -77.103662],
 31332: [38.918199, -77.027171],
 31333: [38.939674, -77.075277],
 31334: [38.935839, -77.106913],
 31335: [38.902677, -77.035866],
 31336: [38.906622, -77.023885],
 31337: [38.912181, -77.066074],
 31338: [38.935842, -77.058468],
 31339: [38.934784, -77.041362],
 31380: [38.949366, -77.350396],
 31381: [38.927943, -77.220829],
 31383: [38.95937, -77.331794],
 31385: [38.918988, -77.21246],
 31386: [38.881436, -77.230377],
 31387: [38.868545, -77.282083],
 31389: [38.869114, -77.271538],
 31390: [38.916501, -77.090911],
 31391: [38.933899, -77.086263],
 31392: [38.9257, -77.079119],
 31393: [38.941808, -77.07643],
 31394: [38.930316, -77.083704],
 31395: [38.931349, -77.077214],
 31396: [38.879256, -77.233583],
 31397: [38.868979, -77.275484],
 31398: [38.930767, -77.241436],
 31399: [38.916908, -77.213879],
 31400: [38.936684, -77.024181],
 31401: [38.9375, -77.0328],
 31402: [38.947774, -77.032818],
 31403: [38.956556, -77.019814],
 31404: [38.9418, -77.0251],
 31405: [38.949662, -77.027333],
 31406: [38.942475, -77.032678],
 31407: [38.956432, -77.032947],
 31408: [38.975219, -77.016855],
 31411: [38.961339, -77.027855],
 31412: [38.957463, -77.002239],
 31413: [38.968871, -77.016263],
 31414: [38.967505, -77.027976],
 31415: [38.95674, -77.02791],
 31416: [38.969489, -77.033509],
 31417: [38.947962, -77.02155],
 31418: [38.951596, -77.012808],
 31419: [38.932128, -77.0235],
 31420: [38.942146, -77.038684],
 31421: [38.942025, -77.018221],
 31422: [38.965775, -77.068626],
 31423: [38.958098, -77.013821],
 31424: [38.953715, -77.025613],
 31425: [38.976061, -77.026747],
 31426: [38.936228, -77.027163],
 31427: [38.967492, -77.007003],
 31428: [38.975739, -77.066409],
 31500: [38.919077, -77.000648],
 31501: [38.933668, -76.991016],
 31502: [38.9346, -76.9955],
 31503: [38.9126, -77.0135],
 31504: [38.932457, -76.993534],
 31505: [38.910972, -77.00495],
 31506: [38.915417, -77.012289],
 31507: [38.928743, -77.012457],
 31508: [38.90509, -76.9941],
 31509: [38.912659, -77.017669],
 31510: [38.927095, -76.978924],
 31511: [38.928644, -76.990955],
 31512: [38.903732, -76.987211],
 31513: [38.918155, -77.004746],
 31514: [38.927497, -76.997194],
 31515: [38.952369, -77.002721],
 31516: [38.920682, -76.995876],
 31517: [38.907908, -76.99707],
 31518: [38.915604, -76.983683],
 31519: [38.908643, -77.012365],
 31520: [38.91263, -76.971923],
 31521: [38.93293, -76.979517],
 31522: [38.914751, -77.00356],
 31523: [38.915, -77.0078],
 31524: [38.907444, -76.986813],
 31525: [38.906299, -76.983221],
 31526: [38.9243, -76.9859],
 31527: [38.912524, -77.008798],
 31528: [38.938889, -76.997226],
 31529: [38.924144, -77.002098],
 31530: [38.910993, -76.985854],
 31531: [38.922404, -76.996023],
 31532: [38.907316, -77.000698],
 31533: [38.911214, -77.002257],
 31534: [38.932243, -76.996133],
 31535: [38.922489, -76.99267],
 31536: [38.907287, -76.999167],
 31537: [38.921641, -76.955687],
 31538: [38.9252, -76.964896],
 31539: [38.921986, -76.960696],
 31540: [38.907073, -77.002109],
 31541: [38.937849, -76.993509],
 31542: [38.943596, -76.990157],
 31543: [38.930774, -76.972851],
 31544: [38.945068, -76.978783],
 31545: [38.941733, -76.980378],
 31546: [38.948307, -76.991829],
 31600: [38.90304, -77.019027],
 31601: [38.8896, -76.9769],
 31602: [38.9308, -77.0315],
 31603: [38.905697, -77.005483],
 31604: [38.899408, -77.015289],
 31605: [38.8851, -77.0023],
 31606: [38.8803, -76.9862],
 31607: [38.882915, -76.987907],
 31608: [38.8792, -76.9953],
 31609: [38.878694, -77.023054],
 31610: [38.886952, -76.996806],
 31611: [38.900427, -76.98825],
 31612: [38.894841, -76.995916],
 31613: [38.884095, -76.995234],
 31614: [38.899983, -76.991383],
 31615: [38.899972, -76.998347],
 31616: [38.900412, -77.001949],
 31617: [38.900413, -76.982872],
 31618: [38.889955, -77.000349],
 31619: [38.890461, -76.988355],
 31620: [38.897222, -77.019347],
 31621: [38.895344, -77.016106],
 31622: [38.894832, -76.987633],
 31623: [38.89696, -77.00493],
 31624: [38.897446, -77.009888],
 31625: [38.881185, -77.001828],
 31626: [38.88732, -76.983569],
 31627: [38.90547, -77.00213],
 31628: [38.878854, -77.005727],
 31629: [38.889988, -76.995193],
 31630: [38.889908, -76.983326],
 31631: [38.897274, -76.994749],
 31632: [38.897195, -76.983575],
 31633: [38.887312, -77.025762],
 31634: [38.87501, -77.0024],
 31635: [38.876737, -76.994468],
 31636: [38.907333, -77.01536],
 31637: [38.899703, -77.008911],
 31638: [38.900358, -77.012108],
 31639: [38.89967, -77.003666],
 31640: [38.896226, -76.992786],
 31641: [38.894972, -77.003135],
 31642: [38.902406, -77.016005],
 31643: [38.884916, -77.005965],
 31644: [38.882489, -76.990121],
 31645: [38.902932, -76.998405],
 31646: [38.88044, -77.025236],
 31647: [38.89222, -76.99602],
 31648: [38.869683, -77.010815],
 31649: [38.931991, -77.032956],
 31650: [38.876893, -77.006072],
 31651: [38.931322, -77.028247],
 31652: [38.876751, -77.000736],
 31653: [38.902674, -77.021392],
 31654: [38.876211, -77.012443],
 31655: [38.897108, -77.011616],
 31656: [38.901935, -76.978627],
 31657: [38.892934, -76.998273],
 31658: [38.897808, -76.979634],
 31659: [38.885908, -76.991476],
 31660: [38.902732, -76.99515],
 31661: [38.899942, -76.994897],
 31662: [38.902386, -77.005649],
 31663: [38.884058, -76.986385],
 31664: [38.866277, -77.010551],
 31665: [38.885483, -76.977187],
 31666: [38.881117, -77.017699],
 31667: [38.863743, -77.013814],
 31668: [38.871841, -77.00591],
 31669: [38.876823, -77.002161],
 31670: [38.901104, -77.028061],
 31671: [38.883318, -76.925315],
 31672: [38.899984, -76.992725],
 31673: [38.874821, -77.020788],
 31674: [38.876747, -77.020945],
 31675: [38.902444, -77.008246],
 31676: [38.870824, -77.011915],
 31677: [38.903819, -77.011987],
 31678: [38.872964, -77.017585],
 31700: [38.861663, -76.969184],
 31701: [38.8692, -76.95964],
 31702: [38.878, -76.9607],
 31703: [38.897063, -76.947446],
 31704: [38.901385, -76.941877],
 31705: [38.894, -76.947974],
 31706: [38.86559, -76.952103],
 31707: [38.889935, -76.93723],
 31708: [38.896544, -76.96012],
 31710: [38.898536, -76.931862],
 31711: [38.908473, -76.933099],
 31712: [38.894474, -76.974828],
 31713: [38.897407, -76.925907],
 31714: [38.891805, -76.913563],
 31715: [38.883011, -76.949709],
 31716: [38.895955, -76.967845],
 31717: [38.900468, -76.947287],
 31718: [38.876227, -76.940981],
 31719: [38.8975, -76.969509],
 31720: [38.878771, -76.97093],
 31721: [38.890461, -76.96128],
 31722: [38.879575, -76.926596],
 31723: [38.872976, -76.935246],
 31724: [38.870353, -76.945283],
 31725: [38.893062, -76.982464],
 31726: [38.883843, -76.957511],
 31727: [38.882458, -76.980715],
 31728: [38.889926, -76.922783],
 31799: [38.87795, -76.96075],
 31800: [38.84323, -76.999376],
 31801: [38.862669, -76.994637],
 31802: [38.867373, -76.988039],
 31803: [38.866611, -76.985238],
 31804: [38.865784, -76.9784],
 31805: [38.873057, -76.971015],
 31806: [38.844711, -76.987823],
 31807: [38.863897, -76.990037],
 31811: [38.831516, -77.008133],
 31812: [38.870695, -76.982359],
 31813: [38.84627, -76.98185],
 31814: [38.84377, -76.97557],
 31815: [38.84623, -76.97703],
 31816: [38.836, -77.0009],
 31817: [38.824481, -77.005497],
 31818: [38.82373, -77.00223],
 31819: [38.81909, -77.01033],
 31820: [38.87335, -76.9834],
 31822: [38.855004, -76.984512],
 31823: [38.835737, -76.983144],
 31824: [38.836646, -76.993589],
 31825: [38.857369, -76.977688],
 31826: [38.869336, -76.978519],
 31827: [38.853124, -77.005174],
 31828: [38.880761, -77.005741],
 31829: [38.860556, -76.98358],
 31830: [38.821563, -77.001095],
 31831: [38.868356, -76.970997],
 31900: [38.898301, -77.118009],
 31901: [38.884829, -77.127671],
 31902: [38.876528, -77.12712],
 31903: [38.799267, -77.0447],
 31904: [38.885321, -77.156427],
 31905: [38.880992, -77.135271],
 31906: [38.812711, -77.061715],
 31907: [38.798133, -77.0487],
 31908: [38.828437, -77.086031],
 31909: [38.843422, -77.064016],
 31910: [38.822738, -77.049265],
 31912: [38.841291, -77.063093],
 31913: [38.820058, -77.062821],
 31914: [38.797557, -77.053766],
 31915: [38.818748, -77.047783],
 31916: [38.829545, -77.047844],
 31917: [38.89386, -77.070862],
 31918: [38.812351, -77.040691],
 31919: [38.876695, -77.112982],
 31920: [38.888282, -77.111066],
 31921: [38.886048, -77.142317],
 31923: [38.859306, -77.102019],
 31924: [38.892556, -77.082089],
 31925: [38.848304, -77.05122],
 31926: [38.879477, -77.114563],
 31927: [38.808161, -77.100796],
 31928: [38.841548, -77.107734],
 31929: [38.793065, -77.049436],
 31930: [38.802738, -77.082463],
 31931: [38.814031, -77.042817],
 31932: [38.800077, -77.129943],
 31933: [38.801947, -77.040293],
 31935: [38.852903, -77.045916],
 31936: [38.864838, -77.056873],
 31937: [38.890863, -77.074893],
 31938: [38.853002, -77.059496],
 31939: [38.895068, -77.07386],
 31940: [38.886256, -77.084262],
 31941: [38.837306, -77.106111],
 31942: [38.809709, -77.135788],
 31943: [38.815842, -77.110014],
 31944: [38.845028, -77.051956],
 31945: [38.854019, -77.118106],
 31946: [38.828887, -77.110588],
 31947: [38.896087, -77.071452],
 31948: [38.88715, -77.16212],
 31949: [38.863556, -77.077201],
 31950: [38.870561, -77.044095],
 31951: [38.857049, -77.116339],
 31952: [38.818509, -77.105564],
 31953: [38.804486, -77.132334],
 31954: [38.811361, -77.109975],
 31955: [38.806002, -77.055911],
 31956: [38.83728, -77.060899],
 31957: [38.824793, -77.085066],
 31958: [38.800703, -77.048043],
 31959: [38.832431, -77.049772],
 31960: [38.836838, -77.057274],
 31961: [38.83863, -77.116206],
 31962: [38.827674, -77.088985],
 31963: [38.814305, -77.11893],
 31964: [38.820152, -77.0939],
 31966: [38.812187, -77.10994],
 31967: [38.809607, -77.128908],
 31968: [38.804801, -77.044676],
 31969: [38.813474, -77.053734],
 31970: [38.817019, -77.050105],
 31971: [38.863508, -77.084259],
 31972: [38.84404, -77.098093],
 31973: [38.874248, -77.104784],
 31974: [38.802893, -77.072558],
 31976: [38.887914, -77.128015],
 31977: [38.904252, -77.127776],
 31978: [38.884533, -77.065803],
 31979: [38.833437, -77.047846],
 31980: [38.864519, -77.083636],
 31981: [38.856645, -77.109609],
 32000: [38.988562, -77.096539],
 32001: [38.985404, -77.023082],
 32002: [38.981103, -77.097426],
 32003: [38.983838, -77.09221],
 32004: [39.096312, -77.192672],
 32005: [39.093783, -77.202501],
 32006: [38.987, -77.029417],
 32007: [39.084125, -77.151291],
 32008: [38.98954, -77.098029],
 32009: [39.094772, -77.145213],
 32010: [38.98128, -77.011336],
 32011: [38.983627, -77.006311],
 32012: [38.995256, -77.029124],
 32013: [38.983525, -77.095367],
 32014: [38.961763, -77.085998],
 32015: [39.120045, -77.156985],
 32016: [39.099376, -77.188014],
 32017: [39.083673, -77.149162],
 32018: [39.123513, -77.15741],
 32019: [38.990249, -77.02935],
 32020: [39.107709, -77.152072],
 32021: [38.982456, -77.091991],
 32022: [39.025387, -77.044563],
 32023: [39.095661, -77.159048],
 32024: [38.989724, -77.023854],
 32025: [38.975, -77.01121],
 32026: [38.977933, -77.006472],
 32027: [38.992375, -77.100104],
 32028: [38.990639, -77.100239],
 32029: [38.977093, -77.094589],
 32030: [39.102099, -77.200322],

- читаю файл bike_share/station_list.csv

In [12]:
station_list = pd.read_csv('../../bike_share/station_list.csv')
station_list

     station_id                  station_name
0         30200  9th St & Pennsylvania Ave NW
1         30201                 9th & G St NW
2         31000           Eads St & 15th St S
3         31001           18th St & S Eads St
4         31002        Crystal Dr & 20th St S
..          ...                           ...
911       32901                6035 Warehouse
912       32902          Motivate Tech Office
913       32906     V1 Warehouse Test Station
914       32909              tech trailer V-1
915       33200     17th St & New York Ave NW

[916 rows x 2 columns]

- записываю точки в dataframe

In [13]:
station_list[['start_lat', 'start_lng']] = station_list['station_id'].map(station_dict).apply(pd.Series).fillna(0)

- оставляю только те станции, которые у которых есть точки

In [14]:
station_list = station_list[(station_list['start_lat'] != 0) & (station_list['start_lng'] != 0)]

- смотрю что получилось

In [15]:
station_list

,station_id,station_name,start_lat,start_lng
0,30200,9th St & Pennsylvania Ave NW,38.894280,-77.023979
1,30201,9th & G St NW,38.898097,-77.023924
2,31000,Eads St & 15th St S,38.858971,-77.053230
3,31001,18th St & S Eads St,38.857250,-77.053320
4,31002,Crystal Dr & 20th St S,38.856425,-77.049232
...,...,...,...,...
908,32608,Falls Church City Hall / Park Ave & Little Fal...,38.885434,-77.173605
909,32609,W Columbia St & N Washington St,38.885621,-77.166917
910,32900,Motivate BX Tech office,38.964406,-77.010759
911,32901,6035 Warehouse,38.963810,-77.010266
915,33200,17th St & New York Ave NW,38.896604,-77.039778

- записываю dataframe в файл csv (data_additional/station_list.scv)

In [16]:
station_list.to_csv('../../data_additional/station_list.scv', index=False)