In [1]:
import pandas as pd
import requests
import os
import json
import time
import random
import glob

## Предварительная обработка данных файла data_additional/station_list.csv

In [14]:
station_list = pd.read_csv('../../data_additional/station_list.csv')
station_list

,station_id,station_name,start_lat,start_lng
0,30200,9th St & Pennsylvania Ave NW,38.894280,-77.023979
1,30201,9th & G St NW,38.898097,-77.023924
2,31000,Eads St & 15th St S,38.858971,-77.053230
3,31001,18th St & S Eads St,38.857250,-77.053320
4,31002,Crystal Dr & 20th St S,38.856425,-77.049232
...,...,...,...,...
908,32608,Falls Church City Hall / Park Ave & Little Fal...,38.885434,-77.173605
909,32609,W Columbia St & N Washington St,38.885621,-77.166917
910,32900,Motivate BX Tech office,38.964406,-77.010759
911,32901,6035 Warehouse,38.963810,-77.010266
912,33200,17th St & New York Ave NW,38.896604,-77.039778

- заменяю '/' на ''  в столбце station_name, что бы записывать потом в json файл

In [15]:
station_list['station_name'] = station_list['station_name'].apply(lambda x: x.replace('/', '') if '/' in x else x)

## Получаем данные о зданиях, которые расположенны в радиусе 300 метров для каждой странции

- написал функцию

In [4]:
def get_data(start_lat, start_lng, distance=300) -> requests.Response:
    """
    Получает данные из OpenStreetMap через Overpass API.

    :param start_lat: широта
    :param start_lng: долгота
    :param distance: радиус поиска в метрах
    :return: Response
    """

    query = f"""
    [out:json][timeout:60];
    node["amenity"](around:{distance},{start_lat},{start_lng});
    out body;
    """

    url = "https://overpass-api.de/api/interpreter"

    headers = {
        "User-Agent": "my-overpass-script/1.0",
        "Accept": "application/json",
        "Content-Type": "text/plain"
    }

    response = requests.post(
        url=url,
        data=query,
        headers=headers,
        timeout=120
    )

    return response

- написал скрипт что бы собрать данные (пришлось делать много обработок так как overpass не может выдеражать большую нагрузку)

In [5]:
for row in station_list.itertuples(index=False):
    station_id = row.station_id
    station_name = row.station_name
    lat = row.start_lat
    lng = row.start_lng

    success = False

    for attempt in range(5):
        try:
            response = get_data(lat, lng)

            if response.status_code == 200:
                data = response.json()

                file_path = os.path.join('../../overpass_data/data_about_build', f"{station_id}_{station_name}.json")

                with open(file_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, ensure_ascii=False, indent=2)

                print(station_id, "✅ saved")
                success = True
                break

            elif response.status_code == 429:
                sleep_time = 20 * (attempt + 1)
                print(station_id, "⚠ 429, sleep", sleep_time)
                time.sleep(sleep_time)

            else:
                print(station_id, "error:", response.status_code)
                time.sleep(5)

        except Exception as e:
            print(station_id, "exception:", e)
            time.sleep(10)

    if not success:
        print(station_id, "❌ failed after 5 attempts")

    # мягкий рандомный sleep между станциями
    time.sleep(random.uniform(2, 5))

30200 ✅ saved
30201 error: 504
30201 ✅ saved
31000 ✅ saved
31001 ⚠ 429, sleep 20
31001 error: 504
31001 ✅ saved
31002 ✅ saved
31003 ✅ saved
31004 ✅ saved
31005 ⚠ 429, sleep 20
31005 error: 504
31005 ✅ saved
31006 ✅ saved
31006 ✅ saved
31007 ⚠ 429, sleep 20
31007 ✅ saved
31009 ✅ saved
31010 ✅ saved
31011 ✅ saved
31012 ⚠ 429, sleep 20
31012 ✅ saved
31013 ✅ saved
31014 ⚠ 429, sleep 20
31014 ✅ saved
31014 error: 504
31014 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31014 ✅ saved
31015 ✅ saved
31015 ✅ saved
31016 ✅ saved
31017 ⚠ 429, sleep 20
31017 ✅ saved
31018 ✅ saved
31019 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31019 ✅ saved
31020 ⚠ 429, sleep 20
31020 ✅ saved
31021 ✅ saved
31022 ✅ saved
31023 ✅ saved
31024 ✅ saved
31025 ✅ saved
31026 ✅ saved
31027 ⚠ 429, sleep 20
31027 ✅ saved
31027 error: 504
31027 ✅ saved
31028 ⚠ 429, sleep 20
31028 ✅ saved
31029 ✅ saved
31030 ✅ saved
31030 ✅ saved
31031 ✅ saved
31032 ✅ saved
31033 ✅ saved
31034 ✅ saved
31035 error: 504
31035 ✅ saved
31036 ✅ saved
31037 ✅ saved
31038 ⚠ 429, sleep 20
31038 ✅ saved
31039 ✅ saved
31040 ✅ saved
31040 ✅ saved
31041 ✅ saved
31042 error: 504
31042 error: 504
31042 error: 504
31042 ✅ saved
31043 ✅ saved
31043 ✅ saved
31043 ✅ saved
31044 ✅ saved
31045 ⚠ 429, sleep 20
31045 error: 504
31045 ✅ saved
31046 ✅ saved
31047 ✅ saved
31047 ⚠ 429, sleep 20
31047 ✅ saved
31048 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31048 ✅ saved
31049 ✅ saved
31049 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31049 error: 504
31049 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31049 ✅ saved
31050 ✅ saved
31051 error: 504
31051 ✅ saved
31051 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31051 error: 504
31051 ✅ saved
31052 error: 504
31052 ✅ saved
31053 error: 504
31053 error: 504
31053 ✅ saved
31054 ✅ saved
31054 ✅ saved
31055 ⚠ 429, sleep 20
31055 ✅ saved
31056 error: 504
31056 ✅ saved
31056 ⚠ 429, sleep 20
31056 ✅ saved
31057 ✅ saved
31057 error: 504
31057 error: 504
31057 ✅ saved
31058 ✅ saved
31058 ⚠ 429, sleep 20
31058 ✅ saved
31059 ⚠ 429, sleep 20
31059 ✅ saved
31059 ✅ saved
31060 ⚠ 429, sleep 20
31060 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31060 ✅ saved
31061 ✅ saved
31061 ✅ saved
31062 error: 504
31062 ✅ saved
31063 exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
31063 ✅ saved
31063 ✅ saved
31064 ✅ saved
31065 ✅ saved
31065 ⚠ 429, sleep 20
31065 error: 504
31065 ✅ saved
31066 ✅ saved
31067 ⚠ 429, sleep 20
31067 ✅ saved
31068 ✅ saved
31069 ✅ saved
31069 ✅ saved
31070 ⚠ 429, sleep 20
31070 ✅ saved
31071 ✅ saved
31072 ✅ saved
31073 ✅ saved
31074 ✅ saved
31075 exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
31075 error: 504
31075 ✅ saved
31076 ✅ saved
31076 ✅ saved
31077 ✅ saved
31078 ✅ saved
31079 ✅ saved
31079 ✅ saved
31080 ⚠ 429, sleep 20
31080 ✅ saved
31080 ✅ saved
31081 ✅ saved
31082 ⚠ 429, sleep 20
31082 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31082 error: 504
31082 error: 504
31082 ✅ saved
31083 ✅ saved
31084 ✅ saved
31085 ✅ saved
31086 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31086 ✅ saved
31087 ✅ saved
31088 ✅ saved
31089 ✅ saved
31090 ⚠ 429, sleep 20
31090 ✅ saved
31091 ✅ saved
31092 ✅ saved
31092 ✅ saved
31093 ⚠ 429, sleep 20
31093 ✅ saved
31094 ✅ saved
31094 ✅ saved
31094 ✅ saved
31095 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31095 ✅ saved
31096 error: 504
31096 ✅ saved
31096 ✅ saved
31097 ✅ saved
31098 ✅ saved
31099 ✅ saved
31100 ✅ saved
31101 error: 504
31101 ✅ saved
31102 ✅ saved
31103 error: 504
31103 ✅ saved
31103 ✅ saved
31104 ✅ saved
31105 ✅ saved
31106 error: 504
31106 error: 504
31106 error: 504
31106 ✅ saved
31107 ✅ saved
31108 ✅ saved
31109 ✅ saved
31109 ✅ saved
31110 ✅ saved
31111 ✅ saved
31112 ✅ saved
31113 ✅ saved
31114 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31114 error: 504
31114 ✅ saved
31115 error: 504
31115 ✅ saved
31116 ⚠ 429, sleep 20
31116 ⚠ 429, sleep 40
31116 ✅ saved
31117 ✅ saved
31117 ✅ saved
31118 ✅ saved
31119 ✅ saved
31120 ✅ saved
31120 ✅ saved
31121 ✅ saved
31122 ✅ saved
31123 ✅ saved
31124 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31124 ✅ saved
31125 ✅ saved
31126 ⚠ 429, sleep 20
31126 ✅ saved
31127 ✅ saved
31128 error: 504
31128 ✅ saved
31129 ✅ saved
31130 error: 504
31130 ✅ saved
31131 ✅ saved
31132 ✅ saved
31133 ✅ saved
31134 ⚠ 429, sleep 20
31134 error: 504
31134 ✅ saved
31135 ✅ saved
31136 ⚠ 429, sleep 20
31136 ✅ saved
31137 ✅ saved
31138 ✅ saved
31200 error: 504
31200 ✅ saved
31201 ⚠ 429, sleep 20
31201 ✅ saved
31202 ✅ saved
31203 ⚠ 429, sleep 20
31203 ✅ saved
31203 ✅ saved
31204 ✅ saved
31205 ✅ saved
31206 error: 504
31206 ✅ saved
31207 ⚠ 429, sleep 20
31207 ✅ saved
31207 ✅ saved
31208 ✅ saved
31209 ✅ saved
31209 ✅ saved
31210 ✅ saved
31211 ✅ saved
31212 ✅ saved
31212 ✅ saved
31213 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31213 ✅ saved
31214 ⚠ 429, sleep 20
31214 ✅ saved
31215 ✅ saved
31216 ⚠ 429, sleep 20
31216 ✅ saved
31217 ✅ saved
31218 ✅ saved
31219 ✅ saved
31220 ✅ saved
31220 ✅ saved
31220 ✅ saved
31221 ⚠ 429, sleep 20
31221 ✅ saved
31222 ⚠ 429, sleep 20
31222 ✅ saved
31222 ✅ saved
31223 ✅ saved
31224 ✅ saved
31225 ⚠ 429, sleep 20
31225 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31225 ✅ saved
31226 ✅ saved
31227 ✅ saved
31228 ⚠ 429, sleep 20
31228 ✅ saved
31229 ✅ saved
31230 ✅ saved
31231 ✅ saved
31231 ✅ saved
31232 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31232 ✅ saved
31233 ✅ saved
31234 ⚠ 429, sleep 20
31234 ✅ saved
31235 ✅ saved
31236 ✅ saved
31237 ⚠ 429, sleep 20
31237 ✅ saved
31238 ✅ saved
31239 ⚠ 429, sleep 20
31239 ✅ saved
31240 error: 504
31240 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31240 ✅ saved
31241 ✅ saved
31242 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31242 ✅ saved
31243 ✅ saved
31244 ✅ saved
31245 ✅ saved
31246 ✅ saved
31247 error: 504
31247 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31247 ✅ saved
31248 ✅ saved
31249 error: 504
31249 ✅ saved
31250 ✅ saved
31251 ⚠ 429, sleep 20
31251 ✅ saved
31252 ✅ saved
31253 ✅ saved
31253 error: 504
31253 ✅ saved
31254 ✅ saved
31255 ✅ saved
31256 ✅ saved
31257 ⚠ 429, sleep 20
31257 ✅ saved
31258 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31258 ✅ saved
31259 ✅ saved
31260 ✅ saved
31261 ⚠ 429, sleep 20
31261 ✅ saved
31261 ✅ saved
31262 ✅ saved
31263 ⚠ 429, sleep 20
31263 ✅ saved
31264 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31264 ✅ saved
31265 ✅ saved
31266 ✅ saved
31267 ✅ saved
31268 ✅ saved
31269 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31269 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31269 ✅ saved
31270 error: 504
31270 ✅ saved
31271 error: 504
31271 error: 504
31271 error: 504
31271 error: 504
31271 ✅ saved
31272 error: 504
31272 ✅ saved
31273 error: 504
31273 ⚠ 429, sleep 40
31273 ✅ saved
31274 ✅ saved
31275 ✅ saved
31276 ⚠ 429, sleep 20
31276 error: 504
31276 ✅ saved
31277 ✅ saved
31278 ⚠ 429, sleep 20
31278 ✅ saved
31279 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31279 ✅ saved
31280 ✅ saved
31281 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31281 ✅ saved
31282 ✅ saved
31283 ⚠ 429, sleep 20
31283 ✅ saved
31284 ✅ saved
31285 ✅ saved
31286 ✅ saved
31287 ⚠ 429, sleep 20
31287 ✅ saved
31288 ✅ saved
31289 ✅ saved
31290 ✅ saved
31291 error: 504
31291 ✅ saved
31292 ✅ saved
31293 error: 504
31293 ✅ saved
31293 ✅ saved
31294 ✅ saved
31295 error: 504
31295 ✅ saved
31296 ✅ saved
31297 ✅ saved
31298 ⚠ 429, sleep 20
31298 ✅ saved
31299 ✅ saved
31300 ✅ saved
31301 ⚠ 429, sleep 20
31301 error: 504
31301 ✅ saved
31302 ✅ saved
31303 ✅ saved
31304 ✅ saved
31305 ✅ saved
31305 ✅ saved
31306 ⚠ 429, sleep 20
31306 error: 504
31306 ✅ saved
31307 ✅ saved
31308 ✅ saved
31309 ✅ saved
31310 ⚠ 429, sleep 20
31310 ✅ saved
31311 exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
31311 ✅ saved
31312 ✅ saved
31313 ✅ saved
31314 ✅ saved
31315 ✅ saved
31316 ✅ saved
31317 error: 504
31317 ✅ saved
31318 ✅ saved
31319 ✅ saved
31320 ✅ saved
31321 error: 504
31321 ✅ saved
31322 ✅ saved
31323 error: 504
31323 ✅ saved
31324 ✅ saved
31325 ✅ saved
31326 ⚠ 429, sleep 20
31326 ✅ saved
31327 ✅ saved
31328 ✅ saved
31329 ✅ saved
31330 ✅ saved
31331 ✅ saved
31331 ✅ saved
31332 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31332 error: 504
31332 ✅ saved
31332 ✅ saved
31333 ✅ saved
31334 ✅ saved
31335 ✅ saved
31336 ✅ saved
31337 ✅ saved
31338 ✅ saved
31339 ✅ saved
31339 ✅ saved
31380 ✅ saved
31380 ✅ saved
31381 ✅ saved
31383 ⚠ 429, sleep 20
31383 ✅ saved
31385 ✅ saved
31386 ✅ saved
31387 error: 504
31387 ✅ saved
31389 ✅ saved
31390 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31390 ✅ saved
31391 ✅ saved
31392 ✅ saved
31393 ✅ saved
31394 ✅ saved
31395 ✅ saved
31396 ✅ saved
31397 ✅ saved
31398 ✅ saved
31399 ✅ saved
31400 ✅ saved
31401 ✅ saved
31401 ✅ saved
31402 ✅ saved
31403 ✅ saved
31404 ✅ saved
31405 ✅ saved
31406 error: 504
31406 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31406 ✅ saved
31407 ✅ saved
31408 ✅ saved
31411 ✅ saved
31412 ⚠ 429, sleep 20
31412 ✅ saved
31413 ✅ saved
31414 ✅ saved
31415 ✅ saved
31416 ✅ saved
31416 ✅ saved
31417 ⚠ 429, sleep 20
31417 ✅ saved
31418 ✅ saved
31419 ✅ saved
31420 ✅ saved
31421 ⚠ 429, sleep 20
31421 ✅ saved
31422 ✅ saved
31422 ✅ saved
31423 ✅ saved
31424 ✅ saved
31425 ✅ saved
31426 ✅ saved
31427 ✅ saved
31428 ✅ saved
31500 ✅ saved
31501 ✅ saved
31502 ✅ saved
31502 ✅ saved
31503 ✅ saved
31504 ⚠ 429, sleep 20
31504 error: 504
31504 ✅ saved
31505 ✅ saved
31506 ✅ saved
31507 ✅ saved
31508 ⚠ 429, sleep 20
31508 ✅ saved
31509 ✅ saved
31510 ✅ saved
31511 error: 504
31511 error: 504
31511 ✅ saved
31512 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31512 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31512 ✅ saved
31513 ✅ saved
31514 ⚠ 429, sleep 20
31514 ✅ saved
31515 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31515 ✅ saved
31516 ✅ saved
31517 ✅ saved
31518 ✅ saved
31519 ✅ saved
31520 ⚠ 429, sleep 20
31520 ✅ saved
31521 ✅ saved
31522 ✅ saved
31523 ✅ saved
31524 ✅ saved
31525 error: 504
31525 ✅ saved
31526 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31526 error: 504
31526 ✅ saved
31527 ✅ saved
31528 ✅ saved
31528 ⚠ 429, sleep 20
31528 ✅ saved
31529 ✅ saved
31530 ✅ saved
31531 ✅ saved
31532 ✅ saved
31533 ⚠ 429, sleep 20
31533 ✅ saved
31534 ✅ saved
31535 ✅ saved
31535 ✅ saved
31536 ⚠ 429, sleep 20
31536 ✅ saved
31537 ✅ saved
31538 ✅ saved
31539 ✅ saved
31540 ✅ saved
31541 ✅ saved
31542 ✅ saved
31543 ✅ saved
31544 ✅ saved
31545 ⚠ 429, sleep 20
31545 ✅ saved
31546 error: 504
31546 error: 504
31546 ✅ saved
31600 ✅ saved
31601 ✅ saved
31602 ⚠ 429, sleep 20
31602 ✅ saved
31603 ✅ saved
31604 ✅ saved
31605 ✅ saved
31606 ✅ saved
31607 ✅ saved
31608 ✅ saved
31609 ✅ saved
31610 ✅ saved
31611 ✅ saved
31612 ✅ saved
31613 ✅ saved
31613 ⚠ 429, sleep 20
31613 ✅ saved
31614 ✅ saved
31615 ✅ saved
31616 ✅ saved
31617 ✅ saved
31618 ✅ saved
31619 ✅ saved
31620 error: 504
31620 ✅ saved
31621 ✅ saved
31622 ✅ saved
31623 error: 504
31623 ✅ saved
31624 ✅ saved
31625 ✅ saved
31626 ⚠ 429, sleep 20
31626 ✅ saved
31627 ✅ saved
31627 ✅ saved
31628 ✅ saved
31628 ⚠ 429, sleep 20
31628 ✅ saved
31629 ✅ saved
31630 ✅ saved
31631 ✅ saved
31632 ⚠ 429, sleep 20
31632 ✅ saved
31633 error: 504
31633 error: 504
31633 ✅ saved
31634 ✅ saved
31635 ✅ saved
31636 ✅ saved
31637 error: 504
31637 ✅ saved
31638 ✅ saved
31639 ✅ saved
31640 error: 504
31640 error: 504
31640 ✅ saved
31641 ✅ saved
31642 ✅ saved
31642 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31642 ⚠ 429, sleep 40
31642 ✅ saved
31643 ✅ saved
31644 ✅ saved
31645 ⚠ 429, sleep 20
31645 ✅ saved
31646 ✅ saved
31647 ⚠ 429, sleep 20
31647 ✅ saved
31648 ✅ saved
31649 ✅ saved
31650 ✅ saved
31651 ✅ saved
31652 ✅ saved
31653 ✅ saved
31654 error: 504
31654 error: 504
31654 ✅ saved
31655 ✅ saved
31656 ✅ saved
31657 ⚠ 429, sleep 20
31657 ✅ saved
31658 ✅ saved
31659 ✅ saved
31660 ✅ saved
31660 ⚠ 429, sleep 20
31660 ✅ saved
31661 ✅ saved
31662 ✅ saved
31662 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31662 exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
31662 ✅ saved
31663 ⚠ 429, sleep 20
31663 error: 504
31663 ✅ saved
31664 ✅ saved
31665 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31665 ✅ saved
31666 ✅ saved
31666 ⚠ 429, sleep 20
31666 ✅ saved
31667 ✅ saved
31667 ✅ saved
31668 ✅ saved
31669 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31669 ✅ saved
31669 ✅ saved
31670 ✅ saved
31671 ✅ saved
31672 ⚠ 429, sleep 20
31672 ✅ saved
31673 ✅ saved
31674 ✅ saved
31675 ✅ saved
31676 ✅ saved
31677 ⚠ 429, sleep 20
31677 ✅ saved
31678 ✅ saved
31700 ✅ saved
31700 ✅ saved
31701 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
31701 error: 504
31701 ✅ saved
31702 ✅ saved
31703 error: 504
31703 ✅ saved
31704 ✅ saved
31705 ✅ saved

- нужно посмотреть какие станции не загрузились

## Получаем данные о парках, которые расположенны в радиусе 300 метров для каждой странции

- написал функцию для извлечения данных о парках

In [ ]:
def get_data_about_parks(start_lat, start_lng, distance=300) -> requests.Response:
    """
    Получает данные из OpenStreetMap через Overpass API.

    :param start_lat: широта
    :param start_lng: долгота
    :param distance: радиус поиска в метрах
    :return: Response
    """

    query = f"""
    [out:json][timeout:60];
    (
    way["leisure"="park"](around:{distance},{start_lat},{start_lng});
    relation["leisure"="park"](around:{distance},{start_lat},{start_lng});
    );
    out geom;
    """

    url = "https://overpass-api.de/api/interpreter"

    headers = {
        "User-Agent": "my-overpass-script/1.0",
        "Accept": "application/json",
        "Content-Type": "text/plain"
    }

    response = requests.post(
        url=url,
        data=query,
        headers=headers,
        timeout=120
    )

    return response

- использовал библиотеку glob для того, что бы понять какие станции уже были выгружаны

In [38]:
json_files = glob.glob("../../overpass_data/data_about_parks/*.json")
json_files

['../../overpass_data/data_about_parks\\30200_9th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_parks\\30201_9th & G St NW.json',
 '../../overpass_data/data_about_parks\\31000_Eads St & 15th St S.json',
 '../../overpass_data/data_about_parks\\31001_18th St & S Eads St.json',
 '../../overpass_data/data_about_parks\\31002_Crystal Dr & 20th St S.json',
 '../../overpass_data/data_about_parks\\31003_Crystal Dr & 15th St S.json',
 '../../overpass_data/data_about_parks\\31004_Aurora Hills Cmty Ctr  18th St & S Hayes St.json',
 '../../overpass_data/data_about_parks\\31005_Pentagon City Metro  12th St & S Hayes St.json',
 '../../overpass_data/data_about_parks\\31006_Army Navy Dr & S Joyce St.json',
 '../../overpass_data/data_about_parks\\31006_Pentagon Row Plaza  Army Navy Dr & Joyce St.json',
 '../../overpass_data/data_about_parks\\31007_Crystal City Metro  18th St & S Bell St.json',
 '../../overpass_data/data_about_parks\\31009_Crystal Dr & 27th St S.json',
 '../../overpass_data/data_about_parks\\31010_S Glebe Rd & Potomac Ave.json',
 '../../overpass_data/data_about_parks\\31011_Crystal Dr & 23rd St S.json',
 '../../overpass_data/data_about_parks\\31012_Clark St & 26th St S.json',
 '../../overpass_data/data_about_parks\\31013_Eads St & 22nd St S.json',
 '../../overpass_data/data_about_parks\\31014_19th St N & Ft Myer Dr.json',
 '../../overpass_data/data_about_parks\\31014_Lynn St & 19th St North.json',
 '../../overpass_data/data_about_parks\\31015_Rosslyn Metro  Wilson Blvd & Ft Myer Dr.json',
 '../../overpass_data/data_about_parks\\31015_Wilson Blvd & Ft Myer Dr.json',
 '../../overpass_data/data_about_parks\\31016_Clarendon Blvd & Pierce St.json',
 '../../overpass_data/data_about_parks\\31017_Wilson Blvd & N Uhle St.json',
 '../../overpass_data/data_about_parks\\31018_Rhodes St & 16th St N.json',
 '../../overpass_data/data_about_parks\\31019_Wilson Blvd & N Edgewood St.json',
 '../../overpass_data/data_about_parks\\31020_Wilson Blvd & N Franklin Rd.json',
 '../../overpass_data/data_about_parks\\31021_Clarendon Blvd & N Fillmore St.json',
 '../../overpass_data/data_about_parks\\31022_Clarendon Metro  Wilson Blvd & N Highland St.json',
 '../../overpass_data/data_about_parks\\31023_Fairfax Dr & Wilson Blvd.json',
 '../../overpass_data/data_about_parks\\31024_Virginia Square Metro  Monroe St & 9th St N.json',
 '../../overpass_data/data_about_parks\\31025_Central Library  Quincy St & 10th St N.json',
 '../../overpass_data/data_about_parks\\31026_Washington Blvd & 10th St N.json',
 '../../overpass_data/data_about_parks\\31027_Key Blvd & N Quinn St.json',
 '../../overpass_data/data_about_parks\\31027_Wilson Blvd & N Quinn St.json',
 '../../overpass_data/data_about_parks\\31028_N Veitch St & Key Blvd.json',
 '../../overpass_data/data_about_parks\\31029_N Veitch St & 20th St N.json',
 '../../overpass_data/data_about_parks\\31030_Langston Blvd & N Adams St.json',
 '../../overpass_data/data_about_parks\\31030_Lee Hwy & N Adams St.json',
 '../../overpass_data/data_about_parks\\31031_15th St & N Scott St.json',
 '../../overpass_data/data_about_parks\\31032_Washington Blvd & 7th St N.json',
 '../../overpass_data/data_about_parks\\31033_Barcroft Community Center.json',
 '../../overpass_data/data_about_parks\\31034_Fairfax Dr & N Randolph St.json',
 '../../overpass_data/data_about_parks\\31035_N Quincy St & Glebe Rd.json',
 '../../overpass_data/data_about_parks\\31036_George Mason Dr & Wilson Blvd.json',
 '../../overpass_data/data_about_parks\\31037_Ballston Metro  Stuart St & 9th St N.json',
 '../../overpass_data/data_about_parks\\31038_Glebe Rd & 11th St N.json',
 '../../overpass_data/data_about_parks\\31039_Wilson Blvd & N Quincy St.json',
 '../../overpass_data/data_about_parks\\31040_GMU  Fairfax Dr & Kenmore St.json',
 '../../overpass_data/data_about_parks\\31040_GMUFairfax Dr & Kenmore St.json',
 '../../overpass_data/data_about_parks\\31041_Prince St & Union St.json',
 '../../overpass_data/data_about_parks\\31042_Market Square  King St & Royal St.json',
 '../../overpass_data/data_about_parks\\31043_N Pitt & Wythe St.json',
 '../../overpass_data/data_about_parks\\31043_Saint Asaph St & Pendleton  St.json',
 '../../overpass_data/data_about_parks\\31043_St Asaph & Pendleton St.json',
 '../../overpass_data/data_about_parks\\31044_King St & Patrick St.json',
 '../../overpass_data/data_about_parks\\31045_Commerce St & Fayette St.json',
 '../../overpass_data/data_about_parks\\31046_Henry St & Pendleton St.json',
 '../../overpass_data/data_about_parks\\31047_Braddock Rd Metro North.json',
 '../../overpass_data/data_about_parks\\31047_Braddock Rd Metro.json',
 '../../overpass_data/data_about_parks\\31048_King St Metro South.json',
 '../../overpass_data/data_about_parks\\31049_Fairfax Dr & N Taylor St.json',
 '../../overpass_data/data_about_parks\\31049_Utah St & 11th St N.json',
 '../../overpass_data/data_about_parks\\31050_Barton St & 10th St N.json',
 '../../overpass_data/data_about_parks\\31051_12th St N & N Pierce St.json',
 '../../overpass_data/data_about_parks\\31051_Arlington Blvd & N Queen St.json',
 '../../overpass_data/data_about_parks\\31052_Potomac Ave & 35th St S.json',
 '../../overpass_data/data_about_parks\\31053_Columbia Pike & S Courthouse Rd.json',
 '../../overpass_data/data_about_parks\\31054_Wakefield High School.json',
 '../../overpass_data/data_about_parks\\31054_Walter Reed Dr & 16th St S.json',
 '../../overpass_data/data_about_parks\\31055_28th St & S Meade St.json',
 '../../overpass_data/data_about_parks\\31056_S Troy St & 26th St S.json',
 '../../overpass_data/data_about_parks\\31056_Troy St & 26th St S.json',
 '../../overpass_data/data_about_parks\\31057_Four Mile Run Dr & S Shirlington Rd.json',
 '../../overpass_data/data_about_parks\\31057_S Four Mile Run Dr & Shirlington Rd.json',
 '../../overpass_data/data_about_parks\\31058_Columbia Pike & Monroe St.json',
 '../../overpass_data/data_about_parks\\31058_Columbia Pike & S Oakland St.json',
 '../../overpass_data/data_about_parks\\31059_Four Mile Run Dr & S Walter Reed Dr.json',
 '../../overpass_data/data_about_parks\\31059_S Four Mile Run Dr & Walter Reed Dr.json',
 '../../overpass_data/data_about_parks\\31060_S Arlington Mill Dr & Campbell Ave.json',
 '../../overpass_data/data_about_parks\\31061_Kenmore St & 24th St S.json',
 '../../overpass_data/data_about_parks\\31061_S Kenmore St & 24th St S.json',
 '../../overpass_data/data_about_parks\\31062_Roosevelt Island.json',
 '../../overpass_data/data_about_parks\\31063_S George Mason & Four Mile Run Dr.json',
 '../../overpass_data/data_about_parks\\31063_S George Mason Dr & S Four Mile Run Dr.json',
 '../../overpass_data/data_about_parks\\31064_Gravelly Point.json',
 '../../overpass_data/data_about_parks\\31065_N Pershing Dr & N Wayne St.json',
 '../../overpass_data/data_about_parks\\31065_Pershing Dr & Wayne St.json',
 '../../overpass_data/data_about_parks\\31066_Columbia Pike & S Orme St.json',
 '../../overpass_data/data_about_parks\\31067_Columbia Pike & S Walter Reed Dr.json',
 '../../overpass_data/data_about_parks\\31068_Arlington Mill Cmty Center  Columbia Pike & S Dinwiddie St.json',
 '../../overpass_data/data_about_parks\\31069_N Pershing Dr & N George Mason Dr.json',
 '../../overpass_data/data_about_parks\\31069_Pershing Dr & N George Mason Dr.json',
 '../../overpass_data/data_about_parks\\31070_Arlington Blvd & Fillmore St.json',
 '../../overpass_data/data_about_parks\\31071_Eads St & 12th St S.json',
 '../../overpass_data/data_about_parks\\31072_31st St & S Woodrow St.json',
 '../../overpass_data/data_about_parks\\31073_Washington Blvd & Walter Reed Dr .json',
 '../../overpass_data/data_about_parks\\31074_TJ Cmty Ctr  2nd St & S Old Glebe Rd.json',
 '../../overpass_data/data_about_parks\\31075_Rolfe St & 9th St S.json',
 '../../overpass_data/data_about_parks\\31076_S Randolph St & Campbell Ave.json',
 '../../overpass_data/data_about_parks\\31076_Shirlington Transit Center  Quincy St & Randolph St.json',
 '../../overpass_data/data_about_parks\\31077_Iwo Jima Memorial  Meade & 14th St N.json',
 '../../overpass_data/data_about_parks\\31078_Arlington Blvd & S George Mason Dr.json',
 '../../overpass_data/data_about_parks\\31079_Langston Blvd & N Cleveland St.json',
 '../../overpass_data/data_about_parks\\31079_Lee Hwy & N Cleveland St.json',
 '../../overpass_data/data_about_parks\\31080_Langston Blvd & N Scott St.json',
 '../../overpass_data/data_about_parks\\31080_Lee Hwy & N Scott St.json',
 '../../overpass_data/data_about_parks\\31081_Duke St & John Carlyle St.json',
 '../../overpass_data/data_about_parks\\31082_Eisenhower Ave & Mill Race Ln.json',
 '../../overpass_data/data_about_parks\\31083_Potomac Greens Dr & Slaters Ln.json',
 '../../overpass_data/data_about_parks\\31084_Ballenger Ave & Dulaney St.json',
 '../../overpass_data/data_about_parks\\31085_Mount Vernon Ave & E Nelson Ave.json',
 '../../overpass_data/data_about_parks\\31086_Mount Vernon Ave & E Del Ray Ave.json',
 '../../overpass_data/data_about_parks\\31087_Monroe Ave & Leslie Ave.json',
 '../../overpass_data/data_about_parks\\31088_Mount Vernon Ave & Kennedy St.json',
 '../../overpass_data/data_about_parks\\31089_Court House Metro  15th St & N Uhle St.json',
 '../../overpass_data/data_about_parks\\31090_Long Bridge Park  Long Bridge Dr & 6th St S.json',
 '../../overpass_data/data_about_parks\\31091_Joyce St & 16th St S.json',
 '../../overpass_data/data_about_parks\\31092_Langston Blvd & N Monroe St.json',
 '../../overpass_data/data_about_parks\\31092_Lee Hwy & N Monroe St.json',
 '../../overpass_data/data_about_parks\\31093_21st St & N Pierce St.json',
 '../../overpass_data/data_about_parks\\31094_Langston Blvd & N Kirkwood Rd.json',
 '../../overpass_data/data_about_parks\\31094_Langston Blvd & N Kirkwood St.json',
 '../../overpass_data/data_about_parks\\31094_Lee Hwy & N Kirkwood Rd.json',
 '../../overpass_data/data_about_parks\\31095_Army Navy Dr & S Nash St.json',
 '../../overpass_data/data_about_parks\\31096_Columbia Pike & S Highland St.json',
 '../../overpass_data/data_about_parks\\31096_Walter Reed Dr & 8th St S.json',
 '../../overpass_data/data_about_parks\\31097_Saint Asaph St & Madison St.json',
 '../../overpass_data/data_about_parks\\31098_King St Metro North  Cameron St.json',
 '../../overpass_data/data_about_parks\\31099_Madison St & N Henry St.json',
 '../../overpass_data/data_about_parks\\31100_19th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_parks\\31101_14th & V St NW.json',
 '../../overpass_data/data_about_parks\\31102_11th & Kenyon St NW.json',
 '../../overpass_data/data_about_parks\\31103_15th & Harvard St NW.json',
 '../../overpass_data/data_about_parks\\31103_16th & Harvard St NW.json',
 '../../overpass_data/data_about_parks\\31104_Adams Mill & Columbia Rd NW.json',
 '../../overpass_data/data_about_parks\\31105_14th & Harvard St NW.json',
 '../../overpass_data/data_about_parks\\31106_Calvert & Biltmore St NW.json',
 '../../overpass_data/data_about_parks\\31107_Lamont & Mt Pleasant NW.json',
 '../../overpass_data/data_about_parks\\31108_4th & M St SW.json',
 '../../overpass_data/data_about_parks\\31109_7th & T St NW.json',
 '../../overpass_data/data_about_parks\\31109_7th St & Florida Ave NW.json',
 '../../overpass_data/data_about_parks\\31110_20th St & Florida Ave NW.json',
 '../../overpass_data/data_about_parks\\31111_10th & U St NW.json',
 '../../overpass_data/data_about_parks\\31112_Harvard St & Adams Mill Rd NW.json',
 '../../overpass_data/data_about_parks\\31113_Columbia Rd & Belmont St NW.json',
 '../../overpass_data/data_about_parks\\31114_18th St & Wyoming Ave NW.json',
 '../../overpass_data/data_about_parks\\31115_Columbia Rd & Georgia Ave NW.json',
 '../../overpass_data/data_about_parks\\31116_California St & Florida Ave NW.json',
 '../../overpass_data/data_about_parks\\31117_15th & Euclid St  NW.json',
 '../../overpass_data/data_about_parks\\31117_15th & Euclid St NW.json',
 '../../overpass_data/data_about_parks\\31118_3rd & Elm St NW.json',
 '../../overpass_data/data_about_parks\\31119_14th & Belmont St NW.json',
 '../../overpass_data/data_about_parks\\31120_10th & Florida Ave NW.json',
 '../../overpass_data/data_about_parks\\31121_Calvert St & Woodley Pl NW.json',
 '../../overpass_data/data_about_parks\\31122_16th & Irving St NW.json',
 '../../overpass_data/data_about_parks\\31123_14th & Girard St NW.json',
 '../../overpass_data/data_about_parks\\31124_14th & Irving St NW.json',
 '../../overpass_data/data_about_parks\\31125_15th & W St NW.json',
 '../../overpass_data/data_about_parks\\31126_11th & Girard St NW.json',
 '../../overpass_data/data_about_parks\\31127_22nd & H St NW.json',
 '../../overpass_data/data_about_parks\\31128_23rd & M St NW.json',
 '../../overpass_data/data_about_parks\\31129_15th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_parks\\31130_7th & S St NW.json',
 '../../overpass_data/data_about_parks\\31131_14th & Otis Pl NW.json',
 '../../overpass_data/data_about_parks\\31132_13th & U St NW.json',
 '../../overpass_data/data_about_parks\\31133_20th & Columbia Rd NW.json',
 '../../overpass_data/data_about_parks\\31134_8th & V St NW.json',
 '../../overpass_data/data_about_parks\\31135_16th & Harvard St NW.json',
 '../../overpass_data/data_about_parks\\31136_11th & Clifton St NW.json',
 '../../overpass_data/data_about_parks\\31137_Park Pl & Rock Creek Church Rd NW.json',
 '../../overpass_data/data_about_parks\\31138_4th & College St NW.json',
 '../../overpass_data/data_about_parks\\31200_Massachusetts Ave & Dupont Circle NW.json',
 '../../overpass_data/data_about_parks\\31201_15th & P St NW.json',
 '../../overpass_data/data_about_parks\\31202_14th & R St NW.json',
 '../../overpass_data/data_about_parks\\31203_14th & Rhode Island Ave NW.json',
 '../../overpass_data/data_about_parks\\31203_14th St & Rhode Island Ave NW.json',
 '../../overpass_data/data_about_parks\\31204_20th & E St NW.json',
 '../../overpass_data/data_about_parks\\31205_21st & I St NW.json',
 '../../overpass_data/data_about_parks\\31206_19th & E Street NW.json',
 '../../overpass_data/data_about_parks\\31207_Georgia Ave & Fairmont St NW.json',
 '../../overpass_data/data_about_parks\\31207_Georgia Ave and Fairmont St NW.json',
 '../../overpass_data/data_about_parks\\31208_M St & New Jersey Ave SE.json',
 '../../overpass_data/data_about_parks\\31209_1st & N St  SE.json',
 '../../overpass_data/data_about_parks\\31209_1st & N St SE.json',
 '../../overpass_data/data_about_parks\\31210_17th St & Rhode Island Ave NW.json',
 '../../overpass_data/data_about_parks\\31211_Kennedy Center.json',
 '../../overpass_data/data_about_parks\\31212_21st & M St NW.json',
 '../../overpass_data/data_about_parks\\31212_New Hampshire Ave & Ward Pl NW.json',
 '../../overpass_data/data_about_parks\\31213_17th & K St NW.json',
 '../../overpass_data/data_about_parks\\31214_17th & Corcoran St NW.json',
 '../../overpass_data/data_about_parks\\31215_Georgetown Harbor  30th St NW.json',
 '../../overpass_data/data_about_parks\\31216_14th St & New York Ave NW.json',
 '../../overpass_data/data_about_parks\\31217_USDA  12th & C St SW.json',
 "../../overpass_data/data_about_parks\\31218_L'Enfant Plaza  7th & C St SW.json",
 '../../overpass_data/data_about_parks\\31219_10th St & Constitution Ave NW.json',
 '../../overpass_data/data_about_parks\\31220_21st & E St NW.json',
 '../../overpass_data/data_about_parks\\31220_21st NW & E St NW.json',
 '../../overpass_data/data_about_parks\\31220_US Dept of State  Virginia Ave & 21st St NW.json',
 '../../overpass_data/data_about_parks\\31221_18th & M St NW.json',
 '../../overpass_data/data_about_parks\\31222_15th St & New York Ave NW.json',
 '../../overpass_data/data_about_parks\\31222_New York Ave & 15th St NW.json',
 '../../overpass_data/data_about_parks\\31223_Convention Center  7th & M St NW.json',
 '../../overpass_data/data_about_parks\\31224_18th & L St NW.json',
 '../../overpass_data/data_about_parks\\31225_C & O Canal & Wisconsin Ave NW.json',
 '../../overpass_data/data_about_parks\\31226_34th St & Wisconsin Ave NW.json',
 '../../overpass_data/data_about_parks\\31227_13th St & New York Ave NW.json',
 '../../overpass_data/data_about_parks\\31228_8th & H St NW.json',
 '../../overpass_data/data_about_parks\\31229_New Hampshire Ave & T St NW.json',
 '../../overpass_data/data_about_parks\\31230_Metro Center  12th & G St NW.json',
 '../../overpass_data/data_about_parks\\31231_14th & D St NW  John A Wilson Building.json',
 '../../overpass_data/data_about_parks\\31231_14th & D St NW  Ronald Reagan Building.json',
 '../../overpass_data/data_about_parks\\31232_7th & F St NW  National Portrait Gallery.json',
 '../../overpass_data/data_about_parks\\31233_17th & K St NW  Farragut Square.json',
 '../../overpass_data/data_about_parks\\31234_20th & O St NW  Dupont South.json',
 '../../overpass_data/data_about_parks\\31235_19th St & Constitution Ave NW.json',
 '../../overpass_data/data_about_parks\\31236_37th & O St NW  Georgetown University.json',
 '../../overpass_data/data_about_parks\\31237_25th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_parks\\31238_14th & G St NW.json',
 '../../overpass_data/data_about_parks\\31239_Rhode Island & Connecticut Ave NW.json',
 '../../overpass_data/data_about_parks\\31240_Ohio Dr & West Basin Dr SW  MLK & FDR Memorials.json',
 '../../overpass_data/data_about_parks\\31241_Thomas Circle.json',
 '../../overpass_data/data_about_parks\\31242_18th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_parks\\31243_4th & C St SW.json',
 '../../overpass_data/data_about_parks\\31244_4th & E St SW.json',
 '../../overpass_data/data_about_parks\\31245_7th & R St NW  Shaw Library.json',
 '../../overpass_data/data_about_parks\\31246_M St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_parks\\31247_Jefferson Dr & 14th St SW.json',
 '../../overpass_data/data_about_parks\\31248_Smithsonian-National Mall  Jefferson Dr & 12th St SW.json',
 '../../overpass_data/data_about_parks\\31249_Jefferson Memorial.json',
 '../../overpass_data/data_about_parks\\31250_20th & L St NW.json',
 '../../overpass_data/data_about_parks\\31251_12th & L St NW.json',
 '../../overpass_data/data_about_parks\\31252_21st St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_parks\\31253_19th & I St NW.json',
 '../../overpass_data/data_about_parks\\31253_19th & K St NW.json',
 '../../overpass_data/data_about_parks\\31254_15th & K St NW.json',
 '../../overpass_data/data_about_parks\\31255_24th & N St NW.json',
 '../../overpass_data/data_about_parks\\31256_10th & E St NW.json',
 '../../overpass_data/data_about_parks\\31257_22nd & I St NW  Foggy Bottom.json',
 '../../overpass_data/data_about_parks\\31258_Lincoln Memorial.json',
 '../../overpass_data/data_about_parks\\31259_20th St & Virginia Ave NW.json',
 '../../overpass_data/data_about_parks\\31260_23rd & E St NW .json',
 '../../overpass_data/data_about_parks\\31261_21st St & Constitution Ave NW.json',
 '../../overpass_data/data_about_parks\\31261_Virginia Ave & C St NW.json',
 '../../overpass_data/data_about_parks\\31262_11th & F St NW.json',
 '../../overpass_data/data_about_parks\\31263_10th & K St NW.json',
 '../../overpass_data/data_about_parks\\31264_6th St & Indiana Ave NW.json',
 '../../overpass_data/data_about_parks\\31265_5th St & Massachusetts Ave NW.json',
 '../../overpass_data/data_about_parks\\31266_11th & M St NW.json',
 '../../overpass_data/data_about_parks\\31267_17th St & Massachusetts Ave NW.json',
 '../../overpass_data/data_about_parks\\31268_12th & U St NW.json',
 '../../overpass_data/data_about_parks\\31269_3rd St & Pennsylvania Ave SE.json',
 '../../overpass_data/data_about_parks\\31270_8th & D St NW.json',
 '../../overpass_data/data_about_parks\\31271_Constitution Ave & 2nd St NWDOL.json',
 '../../overpass_data/data_about_parks\\31272_Washington & Independence Ave SWHHS.json',
 '../../overpass_data/data_about_parks\\31273_Hains PointBuckeye & Ohio Dr SW.json',

- создал переменную station_parks

In [43]:
station_parks = []

- написал цикл где достаю station_id

In [44]:
for file in json_files:
    station_id = file.split('\\')[1][:5]
    station_parks.append(int(station_id))

- далее написал код в котором выбрал те станции, по которым я не получил данные

In [45]:
undownload_parks = station_list[~station_list['station_id'].isin(station_parks)]
undownload_parks

     station_id                     station_name  start_lat  start_lng
570       31827  St. Elizabeths West CampusDHS??  38.853124 -77.005174

- пришлось заменить, потому что не могу записать файл где есть в названии ?

In [ ]:
undownload_parks.loc[:, 'station_name'] = undownload_parks['station_name'].apply(lambda x: x.replace('??', '') if '??' in x else x)

- посмотрел что получилось

In [47]:
undownload_parks

     station_id                   station_name  start_lat  start_lng
570       31827  St. Elizabeths West CampusDHS  38.853124 -77.005174

- написал скрипт что бы собрать данные (пришлось делать много обработок так как overpass не может выдеражать большую нагрузку)

In [48]:
for row in undownload_parks.itertuples(index=False):
    station_id = row.station_id
    station_name = row.station_name
    lat = row.start_lat
    lng = row.start_lng

    success = False

    for attempt in range(5):
        try:
            response = get_data_about_parks(lat, lng)

            if response.status_code == 200:
                data = response.json()

                file_path = os.path.join('../../overpass_data/data_about_parks', f"{station_id}_{station_name}.json")

                with open(file_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, ensure_ascii=False, indent=2)

                print(station_id, "✅ saved")
                success = True
                break

            elif response.status_code == 429:
                sleep_time = 20 * (attempt + 1)
                print(station_id, "⚠ 429, sleep", sleep_time)
                time.sleep(sleep_time)

            else:
                print(station_id, "error:", response.status_code)
                time.sleep(5)

        except Exception as e:
            print(station_id, "exception:", e)
            time.sleep(10)

    if not success:
        print(station_id, "❌ failed after 5 attempts")

    # мягкий рандомный sleep между станциями
    time.sleep(random.uniform(2, 5))

31827 ✅ saved

## Получаем данные о длине велосипедных дорожках, которые расположенны в радиусе 300 метров для каждой странции

- написал функцию для получения данных о длине велосипедных дорожках в радиусе 300 метров

In [16]:
def get_data_about_bike_roads(start_lat, start_lng, distance=300) -> requests.Response:
    """
    Получает данные из OpenStreetMap через Overpass API.

    :param start_lat: широта
    :param start_lng: долгота
    :param distance: радиус поиска в метрах
    :return: Response
    """

    query = f"""
    [out:json][timeout:60];
    (
    way["highway"="cycleway"](around:{distance},{start_lat},{start_lng});
    way["cycleway"](around:{distance},{start_lat},{start_lng});
    way["cycleway:left"](around:{distance},{start_lat},{start_lng});
    way["cycleway:right"](around:{distance},{start_lat},{start_lng});
    way["cycleway:both"](around:{distance},{start_lat},{start_lng});
    );
    out geom;
    """

    url = "https://overpass-api.de/api/interpreter"

    headers = {
        "User-Agent": "my-overpass-script/1.0",
        "Accept": "application/json",
        "Content-Type": "text/plain"
    }

    response = requests.post(
        url=url,
        data=query,
        headers=headers,
        timeout=120
    )

    return response

In [17]:
json_files = glob.glob("../../overpass_data/data_about_bike_roads/*.json")
json_files

['../../overpass_data/data_about_bike_roads\\30200_9th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\30201_9th & G St NW.json',
 '../../overpass_data/data_about_bike_roads\\31000_Eads St & 15th St S.json',
 '../../overpass_data/data_about_bike_roads\\31001_18th St & S Eads St.json',
 '../../overpass_data/data_about_bike_roads\\31002_Crystal Dr & 20th St S.json',
 '../../overpass_data/data_about_bike_roads\\31003_Crystal Dr & 15th St S.json',
 '../../overpass_data/data_about_bike_roads\\31004_Aurora Hills Cmty Ctr  18th St & S Hayes St.json',
 '../../overpass_data/data_about_bike_roads\\31005_Pentagon City Metro  12th St & S Hayes St.json',
 '../../overpass_data/data_about_bike_roads\\31006_Army Navy Dr & S Joyce St.json',
 '../../overpass_data/data_about_bike_roads\\31006_Pentagon Row Plaza  Army Navy Dr & Joyce St.json',
 '../../overpass_data/data_about_bike_roads\\31007_Crystal City Metro  18th St & S Bell St.json',
 '../../overpass_data/data_about_bike_roads\\31009_Crystal Dr & 27th St S.json',
 '../../overpass_data/data_about_bike_roads\\31010_S Glebe Rd & Potomac Ave.json',
 '../../overpass_data/data_about_bike_roads\\31011_Crystal Dr & 23rd St S.json',
 '../../overpass_data/data_about_bike_roads\\31012_Clark St & 26th St S.json',
 '../../overpass_data/data_about_bike_roads\\31013_Eads St & 22nd St S.json',
 '../../overpass_data/data_about_bike_roads\\31014_19th St N & Ft Myer Dr.json',
 '../../overpass_data/data_about_bike_roads\\31014_Lynn St & 19th St North.json',
 '../../overpass_data/data_about_bike_roads\\31015_Rosslyn Metro  Wilson Blvd & Ft Myer Dr.json',
 '../../overpass_data/data_about_bike_roads\\31015_Wilson Blvd & Ft Myer Dr.json',
 '../../overpass_data/data_about_bike_roads\\31016_Clarendon Blvd & Pierce St.json',
 '../../overpass_data/data_about_bike_roads\\31017_Wilson Blvd & N Uhle St.json',
 '../../overpass_data/data_about_bike_roads\\31018_Rhodes St & 16th St N.json',
 '../../overpass_data/data_about_bike_roads\\31019_Wilson Blvd & N Edgewood St.json',
 '../../overpass_data/data_about_bike_roads\\31020_Wilson Blvd & N Franklin Rd.json',
 '../../overpass_data/data_about_bike_roads\\31021_Clarendon Blvd & N Fillmore St.json',
 '../../overpass_data/data_about_bike_roads\\31022_Clarendon Metro  Wilson Blvd & N Highland St.json',
 '../../overpass_data/data_about_bike_roads\\31023_Fairfax Dr & Wilson Blvd.json',
 '../../overpass_data/data_about_bike_roads\\31024_Virginia Square Metro  Monroe St & 9th St N.json',
 '../../overpass_data/data_about_bike_roads\\31025_Central Library  Quincy St & 10th St N.json',
 '../../overpass_data/data_about_bike_roads\\31026_Washington Blvd & 10th St N.json',
 '../../overpass_data/data_about_bike_roads\\31027_Key Blvd & N Quinn St.json',
 '../../overpass_data/data_about_bike_roads\\31027_Wilson Blvd & N Quinn St.json',
 '../../overpass_data/data_about_bike_roads\\31028_N Veitch St & Key Blvd.json',
 '../../overpass_data/data_about_bike_roads\\31029_N Veitch St & 20th St N.json',
 '../../overpass_data/data_about_bike_roads\\31030_Langston Blvd & N Adams St.json',
 '../../overpass_data/data_about_bike_roads\\31030_Lee Hwy & N Adams St.json',
 '../../overpass_data/data_about_bike_roads\\31031_15th St & N Scott St.json',
 '../../overpass_data/data_about_bike_roads\\31032_Washington Blvd & 7th St N.json',
 '../../overpass_data/data_about_bike_roads\\31033_Barcroft Community Center.json',
 '../../overpass_data/data_about_bike_roads\\31034_Fairfax Dr & N Randolph St.json',
 '../../overpass_data/data_about_bike_roads\\31035_N Quincy St & Glebe Rd.json',
 '../../overpass_data/data_about_bike_roads\\31036_George Mason Dr & Wilson Blvd.json',
 '../../overpass_data/data_about_bike_roads\\31037_Ballston Metro  Stuart St & 9th St N.json',
 '../../overpass_data/data_about_bike_roads\\31038_Glebe Rd & 11th St N.json',
 '../../overpass_data/data_about_bike_roads\\31039_Wilson Blvd & N Quincy St.json',
 '../../overpass_data/data_about_bike_roads\\31040_GMU  Fairfax Dr & Kenmore St.json',
 '../../overpass_data/data_about_bike_roads\\31040_GMUFairfax Dr & Kenmore St.json',
 '../../overpass_data/data_about_bike_roads\\31041_Prince St & Union St.json',
 '../../overpass_data/data_about_bike_roads\\31042_Market Square  King St & Royal St.json',
 '../../overpass_data/data_about_bike_roads\\31043_N Pitt & Wythe St.json',
 '../../overpass_data/data_about_bike_roads\\31043_Saint Asaph St & Pendleton  St.json',
 '../../overpass_data/data_about_bike_roads\\31043_St Asaph & Pendleton St.json',
 '../../overpass_data/data_about_bike_roads\\31044_King St & Patrick St.json',
 '../../overpass_data/data_about_bike_roads\\31045_Commerce St & Fayette St.json',
 '../../overpass_data/data_about_bike_roads\\31046_Henry St & Pendleton St.json',
 '../../overpass_data/data_about_bike_roads\\31047_Braddock Rd Metro North.json',
 '../../overpass_data/data_about_bike_roads\\31047_Braddock Rd Metro.json',
 '../../overpass_data/data_about_bike_roads\\31048_King St Metro South.json',
 '../../overpass_data/data_about_bike_roads\\31049_Fairfax Dr & N Taylor St.json',
 '../../overpass_data/data_about_bike_roads\\31049_Utah St & 11th St N.json',
 '../../overpass_data/data_about_bike_roads\\31050_Barton St & 10th St N.json',
 '../../overpass_data/data_about_bike_roads\\31051_12th St N & N Pierce St.json',
 '../../overpass_data/data_about_bike_roads\\31051_Arlington Blvd & N Queen St.json',
 '../../overpass_data/data_about_bike_roads\\31052_Potomac Ave & 35th St S.json',
 '../../overpass_data/data_about_bike_roads\\31053_Columbia Pike & S Courthouse Rd.json',
 '../../overpass_data/data_about_bike_roads\\31054_Wakefield High School.json',
 '../../overpass_data/data_about_bike_roads\\31054_Walter Reed Dr & 16th St S.json',
 '../../overpass_data/data_about_bike_roads\\31055_28th St & S Meade St.json',
 '../../overpass_data/data_about_bike_roads\\31056_S Troy St & 26th St S.json',
 '../../overpass_data/data_about_bike_roads\\31056_Troy St & 26th St S.json',
 '../../overpass_data/data_about_bike_roads\\31057_Four Mile Run Dr & S Shirlington Rd.json',
 '../../overpass_data/data_about_bike_roads\\31057_S Four Mile Run Dr & Shirlington Rd.json',
 '../../overpass_data/data_about_bike_roads\\31058_Columbia Pike & Monroe St.json',
 '../../overpass_data/data_about_bike_roads\\31058_Columbia Pike & S Oakland St.json',
 '../../overpass_data/data_about_bike_roads\\31059_Four Mile Run Dr & S Walter Reed Dr.json',
 '../../overpass_data/data_about_bike_roads\\31059_S Four Mile Run Dr & Walter Reed Dr.json',
 '../../overpass_data/data_about_bike_roads\\31060_S Arlington Mill Dr & Campbell Ave.json',
 '../../overpass_data/data_about_bike_roads\\31061_Kenmore St & 24th St S.json',
 '../../overpass_data/data_about_bike_roads\\31061_S Kenmore St & 24th St S.json',
 '../../overpass_data/data_about_bike_roads\\31062_Roosevelt Island.json',
 '../../overpass_data/data_about_bike_roads\\31063_S George Mason & Four Mile Run Dr.json',
 '../../overpass_data/data_about_bike_roads\\31063_S George Mason Dr & S Four Mile Run Dr.json',
 '../../overpass_data/data_about_bike_roads\\31064_Gravelly Point.json',
 '../../overpass_data/data_about_bike_roads\\31065_N Pershing Dr & N Wayne St.json',
 '../../overpass_data/data_about_bike_roads\\31065_Pershing Dr & Wayne St.json',
 '../../overpass_data/data_about_bike_roads\\31066_Columbia Pike & S Orme St.json',
 '../../overpass_data/data_about_bike_roads\\31067_Columbia Pike & S Walter Reed Dr.json',
 '../../overpass_data/data_about_bike_roads\\31068_Arlington Mill Cmty Center  Columbia Pike & S Dinwiddie St.json',
 '../../overpass_data/data_about_bike_roads\\31069_N Pershing Dr & N George Mason Dr.json',
 '../../overpass_data/data_about_bike_roads\\31069_Pershing Dr & N George Mason Dr.json',
 '../../overpass_data/data_about_bike_roads\\31070_Arlington Blvd & Fillmore St.json',
 '../../overpass_data/data_about_bike_roads\\31071_Eads St & 12th St S.json',
 '../../overpass_data/data_about_bike_roads\\31072_31st St & S Woodrow St.json',
 '../../overpass_data/data_about_bike_roads\\31073_Washington Blvd & Walter Reed Dr .json',
 '../../overpass_data/data_about_bike_roads\\31074_TJ Cmty Ctr  2nd St & S Old Glebe Rd.json',
 '../../overpass_data/data_about_bike_roads\\31075_Rolfe St & 9th St S.json',
 '../../overpass_data/data_about_bike_roads\\31076_S Randolph St & Campbell Ave.json',
 '../../overpass_data/data_about_bike_roads\\31076_Shirlington Transit Center  Quincy St & Randolph St.json',
 '../../overpass_data/data_about_bike_roads\\31077_Iwo Jima Memorial  Meade & 14th St N.json',
 '../../overpass_data/data_about_bike_roads\\31078_Arlington Blvd & S George Mason Dr.json',
 '../../overpass_data/data_about_bike_roads\\31079_Langston Blvd & N Cleveland St.json',
 '../../overpass_data/data_about_bike_roads\\31079_Lee Hwy & N Cleveland St.json',
 '../../overpass_data/data_about_bike_roads\\31080_Langston Blvd & N Scott St.json',
 '../../overpass_data/data_about_bike_roads\\31080_Lee Hwy & N Scott St.json',
 '../../overpass_data/data_about_bike_roads\\31081_Duke St & John Carlyle St.json',
 '../../overpass_data/data_about_bike_roads\\31082_Eisenhower Ave & Mill Race Ln.json',
 '../../overpass_data/data_about_bike_roads\\31083_Potomac Greens Dr & Slaters Ln.json',
 '../../overpass_data/data_about_bike_roads\\31084_Ballenger Ave & Dulaney St.json',
 '../../overpass_data/data_about_bike_roads\\31085_Mount Vernon Ave & E Nelson Ave.json',
 '../../overpass_data/data_about_bike_roads\\31086_Mount Vernon Ave & E Del Ray Ave.json',
 '../../overpass_data/data_about_bike_roads\\31087_Monroe Ave & Leslie Ave.json',
 '../../overpass_data/data_about_bike_roads\\31088_Mount Vernon Ave & Kennedy St.json',
 '../../overpass_data/data_about_bike_roads\\31089_Court House Metro  15th St & N Uhle St.json',
 '../../overpass_data/data_about_bike_roads\\31090_Long Bridge Park  Long Bridge Dr & 6th St S.json',
 '../../overpass_data/data_about_bike_roads\\31091_Joyce St & 16th St S.json',
 '../../overpass_data/data_about_bike_roads\\31092_Langston Blvd & N Monroe St.json',
 '../../overpass_data/data_about_bike_roads\\31092_Lee Hwy & N Monroe St.json',
 '../../overpass_data/data_about_bike_roads\\31093_21st St & N Pierce St.json',
 '../../overpass_data/data_about_bike_roads\\31094_Langston Blvd & N Kirkwood Rd.json',
 '../../overpass_data/data_about_bike_roads\\31094_Langston Blvd & N Kirkwood St.json',
 '../../overpass_data/data_about_bike_roads\\31094_Lee Hwy & N Kirkwood Rd.json',
 '../../overpass_data/data_about_bike_roads\\31095_Army Navy Dr & S Nash St.json',
 '../../overpass_data/data_about_bike_roads\\31096_Columbia Pike & S Highland St.json',
 '../../overpass_data/data_about_bike_roads\\31096_Walter Reed Dr & 8th St S.json',
 '../../overpass_data/data_about_bike_roads\\31097_Saint Asaph St & Madison St.json',
 '../../overpass_data/data_about_bike_roads\\31098_King St Metro North  Cameron St.json',
 '../../overpass_data/data_about_bike_roads\\31099_Madison St & N Henry St.json',
 '../../overpass_data/data_about_bike_roads\\31100_19th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31101_14th & V St NW.json',
 '../../overpass_data/data_about_bike_roads\\31102_11th & Kenyon St NW.json',
 '../../overpass_data/data_about_bike_roads\\31103_15th & Harvard St NW.json',
 '../../overpass_data/data_about_bike_roads\\31103_16th & Harvard St NW.json',
 '../../overpass_data/data_about_bike_roads\\31104_Adams Mill & Columbia Rd NW.json',
 '../../overpass_data/data_about_bike_roads\\31105_14th & Harvard St NW.json',
 '../../overpass_data/data_about_bike_roads\\31106_Calvert & Biltmore St NW.json',
 '../../overpass_data/data_about_bike_roads\\31107_Lamont & Mt Pleasant NW.json',
 '../../overpass_data/data_about_bike_roads\\31108_4th & M St SW.json',
 '../../overpass_data/data_about_bike_roads\\31109_7th & T St NW.json',
 '../../overpass_data/data_about_bike_roads\\31109_7th St & Florida Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31110_20th St & Florida Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31111_10th & U St NW.json',
 '../../overpass_data/data_about_bike_roads\\31112_Harvard St & Adams Mill Rd NW.json',
 '../../overpass_data/data_about_bike_roads\\31113_Columbia Rd & Belmont St NW.json',
 '../../overpass_data/data_about_bike_roads\\31114_18th St & Wyoming Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31115_Columbia Rd & Georgia Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31116_California St & Florida Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31117_15th & Euclid St  NW.json',
 '../../overpass_data/data_about_bike_roads\\31117_15th & Euclid St NW.json',
 '../../overpass_data/data_about_bike_roads\\31118_3rd & Elm St NW.json',
 '../../overpass_data/data_about_bike_roads\\31119_14th & Belmont St NW.json',
 '../../overpass_data/data_about_bike_roads\\31120_10th & Florida Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31120_10th St & Florida Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31121_Calvert St & Woodley Pl NW.json',
 '../../overpass_data/data_about_bike_roads\\31122_16th & Irving St NW.json',
 '../../overpass_data/data_about_bike_roads\\31123_14th & Girard St NW.json',
 '../../overpass_data/data_about_bike_roads\\31124_14th & Irving St NW.json',
 '../../overpass_data/data_about_bike_roads\\31125_15th & W St NW.json',
 '../../overpass_data/data_about_bike_roads\\31126_11th & Girard St NW.json',
 '../../overpass_data/data_about_bike_roads\\31127_22nd & H St NW.json',
 '../../overpass_data/data_about_bike_roads\\31128_23rd & M St NW.json',
 '../../overpass_data/data_about_bike_roads\\31129_15th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31130_7th & S St NW.json',
 '../../overpass_data/data_about_bike_roads\\31131_14th & Otis Pl NW.json',
 '../../overpass_data/data_about_bike_roads\\31132_13th & U St NW.json',
 '../../overpass_data/data_about_bike_roads\\31133_20th & Columbia Rd NW.json',
 '../../overpass_data/data_about_bike_roads\\31134_8th & V St NW.json',
 '../../overpass_data/data_about_bike_roads\\31135_16th & Harvard St NW.json',
 '../../overpass_data/data_about_bike_roads\\31136_11th & Clifton St NW.json',
 '../../overpass_data/data_about_bike_roads\\31137_Park Pl & Rock Creek Church Rd NW.json',
 '../../overpass_data/data_about_bike_roads\\31138_4th & College St NW.json',
 '../../overpass_data/data_about_bike_roads\\31200_Massachusetts Ave & Dupont Circle NW.json',
 '../../overpass_data/data_about_bike_roads\\31201_15th & P St NW.json',
 '../../overpass_data/data_about_bike_roads\\31202_14th & R St NW.json',
 '../../overpass_data/data_about_bike_roads\\31203_14th & Rhode Island Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31204_20th & E St NW.json',
 '../../overpass_data/data_about_bike_roads\\31205_21st & I St NW.json',
 '../../overpass_data/data_about_bike_roads\\31206_19th & E Street NW.json',
 '../../overpass_data/data_about_bike_roads\\31207_Georgia Ave & Fairmont St NW.json',
 '../../overpass_data/data_about_bike_roads\\31207_Georgia Ave and Fairmont St NW.json',
 '../../overpass_data/data_about_bike_roads\\31208_M St & New Jersey Ave SE.json',
 '../../overpass_data/data_about_bike_roads\\31209_1st & N St  SE.json',
 '../../overpass_data/data_about_bike_roads\\31209_1st & N St SE.json',
 '../../overpass_data/data_about_bike_roads\\31210_17th St & Rhode Island Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31211_Kennedy Center.json',
 '../../overpass_data/data_about_bike_roads\\31212_21st & M St NW.json',
 '../../overpass_data/data_about_bike_roads\\31212_New Hampshire Ave & Ward Pl NW.json',
 '../../overpass_data/data_about_bike_roads\\31213_17th & K St NW.json',
 '../../overpass_data/data_about_bike_roads\\31214_17th & Corcoran St NW.json',
 '../../overpass_data/data_about_bike_roads\\31215_Georgetown Harbor  30th St NW.json',
 '../../overpass_data/data_about_bike_roads\\31216_14th St & New York Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31217_USDA  12th & C St SW.json',
 "../../overpass_data/data_about_bike_roads\\31218_L'Enfant Plaza  7th & C St SW.json",
 '../../overpass_data/data_about_bike_roads\\31219_10th St & Constitution Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31220_21st & E St NW.json',
 '../../overpass_data/data_about_bike_roads\\31220_21st NW & E St NW.json',
 '../../overpass_data/data_about_bike_roads\\31221_18th & M St NW.json',
 '../../overpass_data/data_about_bike_roads\\31222_15th St & New York Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31222_New York Ave & 15th St NW.json',
 '../../overpass_data/data_about_bike_roads\\31223_Convention Center  7th & M St NW.json',
 '../../overpass_data/data_about_bike_roads\\31224_18th & L St NW.json',
 '../../overpass_data/data_about_bike_roads\\31225_C & O Canal & Wisconsin Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31226_34th St & Wisconsin Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31227_13th St & New York Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31228_8th & H St NW.json',
 '../../overpass_data/data_about_bike_roads\\31229_New Hampshire Ave & T St NW.json',
 '../../overpass_data/data_about_bike_roads\\31230_Metro Center  12th & G St NW.json',
 '../../overpass_data/data_about_bike_roads\\31231_14th & D St NW  John A Wilson Building.json',
 '../../overpass_data/data_about_bike_roads\\31231_14th & D St NW  Ronald Reagan Building.json',
 '../../overpass_data/data_about_bike_roads\\31232_7th & F St NW  National Portrait Gallery.json',
 '../../overpass_data/data_about_bike_roads\\31233_17th & K St NW  Farragut Square.json',
 '../../overpass_data/data_about_bike_roads\\31234_20th & O St NW  Dupont South.json',
 '../../overpass_data/data_about_bike_roads\\31235_19th St & Constitution Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31236_37th & O St NW  Georgetown University.json',
 '../../overpass_data/data_about_bike_roads\\31237_25th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31238_14th & G St NW.json',
 '../../overpass_data/data_about_bike_roads\\31239_Rhode Island & Connecticut Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31240_Ohio Dr & West Basin Dr SW  MLK & FDR Memorials.json',
 '../../overpass_data/data_about_bike_roads\\31241_Thomas Circle.json',
 '../../overpass_data/data_about_bike_roads\\31242_18th St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31243_4th & C St SW.json',
 '../../overpass_data/data_about_bike_roads\\31244_4th & E St SW.json',
 '../../overpass_data/data_about_bike_roads\\31245_7th & R St NW  Shaw Library.json',
 '../../overpass_data/data_about_bike_roads\\31246_M St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31247_Jefferson Dr & 14th St SW.json',
 '../../overpass_data/data_about_bike_roads\\31248_Smithsonian-National Mall  Jefferson Dr & 12th St SW.json',
 '../../overpass_data/data_about_bike_roads\\31249_Jefferson Memorial.json',
 '../../overpass_data/data_about_bike_roads\\31250_20th & L St NW.json',
 '../../overpass_data/data_about_bike_roads\\31251_12th & L St NW.json',
 '../../overpass_data/data_about_bike_roads\\31252_21st St & Pennsylvania Ave NW.json',
 '../../overpass_data/data_about_bike_roads\\31253_19th & I St NW.json',
 '../../overpass_data/data_about_bike_roads\\31253_19th & K St NW.json',
 '../../overpass_data/data_about_bike_roads\\31254_15th & K St NW.json',
 '../../overpass_data/data_about_bike_roads\\31255_24th & N St NW.json',
 '../../overpass_data/data_about_bike_roads\\31256_10th & E St NW.json',
 '../../overpass_data/data_about_bike_roads\\31257_22nd & I St NW  Foggy Bottom.json',
 '../../overpass_data/data_about_bike_roads\\31258_Lincoln Memorial.json',
 '../../overpass_data/data_about_bike_roads\\31259_20th St & Virginia Ave NW.json',

In [18]:
station_bike_roads = []

In [19]:
for file in json_files:
    station_id = file.split('\\')[1][:5]
    station_bike_roads.append(int(station_id))

In [20]:
undownload_bike_roads = station_list[~station_list['station_id'].isin(station_bike_roads)]
undownload_bike_roads

,station_id,station_name,start_lat,start_lng
687,32015,Crabbs Branch Way & Redland Rd,39.120045,-77.156985
689,32017,Monroe St & Monroe Pl,39.083673,-77.149162
705,32034,Silver Spring Transit Center - Top Level,38.994035,-77.030371
720,32049,WAU Flower Ave & Division St,38.986743,-77.000035
721,32050,Spring St & 2nd Ave,38.997653,-77.034499
...,...,...,...,...
908,32608,Falls Church City Hall Park Ave & Little Fall...,38.885434,-77.173605
909,32609,W Columbia St & N Washington St,38.885621,-77.166917
910,32900,Motivate BX Tech office,38.964406,-77.010759
911,32901,6035 Warehouse,38.963810,-77.010266
912,33200,17th St & New York Ave NW,38.896604,-77.039778

In [21]:
undownload_bike_roads.loc[:, 'station_name'] = undownload_bike_roads[
    'station_name'
].apply(lambda x: x.replace('??', '') if '??' in x else x)

In [22]:
undownload_bike_roads

,station_id,station_name,start_lat,start_lng
687,32015,Crabbs Branch Way & Redland Rd,39.120045,-77.156985
689,32017,Monroe St & Monroe Pl,39.083673,-77.149162
705,32034,Silver Spring Transit Center - Top Level,38.994035,-77.030371
720,32049,WAU Flower Ave & Division St,38.986743,-77.000035
721,32050,Spring St & 2nd Ave,38.997653,-77.034499
...,...,...,...,...
908,32608,Falls Church City Hall Park Ave & Little Fall...,38.885434,-77.173605
909,32609,W Columbia St & N Washington St,38.885621,-77.166917
910,32900,Motivate BX Tech office,38.964406,-77.010759
911,32901,6035 Warehouse,38.963810,-77.010266
912,33200,17th St & New York Ave NW,38.896604,-77.039778

In [23]:
for row in undownload_bike_roads.itertuples(index=False):
    station_id = row.station_id
    station_name = row.station_name
    lat = row.start_lat
    lng = row.start_lng

    success = False

    for attempt in range(5):
        try:
            response = get_data_about_bike_roads(lat, lng)

            if response.status_code == 200:
                data = response.json()

                file_path = os.path.join('../../overpass_data/data_about_bike_roads', f"{station_id}_{station_name}.json")

                with open(file_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, ensure_ascii=False, indent=2)

                print(station_id, "✅ saved")
                success = True
                break

            elif response.status_code == 429:
                sleep_time = 20 * (attempt + 1)
                print(station_id, "⚠ 429, sleep", sleep_time)
                time.sleep(sleep_time)

            else:
                print(station_id, "error:", response.status_code)
                time.sleep(5)

        except Exception as e:
            print(station_id, "exception:", e)
            time.sleep(10)

    if not success:
        print(station_id, "❌ failed after 5 attempts")

    # мягкий рандомный sleep между станциями
    time.sleep(random.uniform(2, 5))

32015 error: 504
32015 error: 504
32015 ✅ saved
32017 error: 504
32017 error: 504
32017 error: 504
32017 ✅ saved
32034 error: 504
32034 ✅ saved
32049 error: 504
32049 error: 504
32049 error: 504
32049 ✅ saved
32050 error: 504
32050 ✅ saved
32054 error: 504
32054 error: 504
32054 error: 504
32054 error: 504
32054 ✅ saved
32064 error: 504
32064 ✅ saved
32074 error: 504
32074 error: 504
32074 error: 504
32074 error: 504
32074 ✅ saved
32075 ✅ saved
32075 ✅ saved
32077 error: 504
32077 error: 504
32077 ✅ saved
32078 ✅ saved
32091 error: 504
32091 error: 504
32091 error: 504
32091 error: 504
32091 ✅ saved
32201 error: 504
32201 ✅ saved
32233 error: 504
32233 ✅ saved
32238 ✅ saved
32239 ⚠ 429, sleep 20
32239 error: 504
32239 error: 504
32239 error: 504
32239 ✅ saved
32240 ✅ saved
32241 ⚠ 429, sleep 20
32241 error: 504
32241 error: 504
32241 ✅ saved
32242 ✅ saved
32242 ⚠ 429, sleep 20
32242 error: 504
32242 error: 504
32242 ✅ saved
32243 ✅ saved
32243 ⚠ 429, sleep 20
32243 ⚠ 429, sleep 40
32243 error: 504
32243 error: 504
32243 ✅ saved
32244 error: 504
32244 ✅ saved
32245 ✅ saved
32246 error: 504
32246 ✅ saved
32247 ⚠ 429, sleep 20
32247 error: 504
32247 error: 504
32247 ✅ saved
32248 error: 504
32248 error: 504
32248 ✅ saved
32249 ✅ saved
32250 error: 504
32250 error: 504
32250 error: 504
32250 ✅ saved
32250 error: 504
32250 ✅ saved
32251 ✅ saved
32252 error: 504
32252 ✅ saved
32253 ⚠ 429, sleep 20
32253 error: 504
32253 error: 504
32253 error: 504
32253 ✅ saved
32255 ✅ saved
32256 error: 504
32256 error: 504
32256 error: 504
32256 error: 504
32256 error: 504
32256 ❌ failed after 5 attempts
32258 ✅ saved
32259 ✅ saved
32260 error: 504
32260 error: 504
32260 error: 504
32260 ✅ saved
32261 ✅ saved
32261 ✅ saved
32262 ✅ saved
32263 error: 504
32263 error: 504
32263 error: 504
32263 ✅ saved
32264 error: 504
32264 error: 504
32264 ✅ saved
32265 error: 504
32265 error: 504
32265 ✅ saved
32266 ✅ saved
32267 ✅ saved
32268 error: 504
32268 error: 504
32268 ✅ saved
32269 error: 504
32269 error: 504
32269 error: 504
32269 ✅ saved
32270 ✅ saved
32270 ✅ saved
32271 ✅ saved
32272 ⚠ 429, sleep 20
32272 ✅ saved
32274 ✅ saved
32275 ✅ saved
32276 error: 504
32276 ✅ saved
32277 error: 504
32277 error: 504
32277 error: 504
32277 error: 504
32277 error: 504
32277 ❌ failed after 5 attempts
32278 error: 504
32278 error: 504
32278 error: 504
32278 error: 504
32278 error: 504
32278 ❌ failed after 5 attempts
32279 error: 504
32279 ✅ saved
32279 ✅ saved
32280 error: 504
32280 error: 504
32280 error: 504
32280 ✅ saved
32281 error: 504
32281 error: 504
32281 error: 504
32281 error: 504
32281 error: 504
32281 ❌ failed after 5 attempts
32282 ✅ saved
32283 ✅ saved
32288 ✅ saved
32288 ✅ saved
32289 ⚠ 429, sleep 20
32289 error: 504
32289 error: 504
32289 ✅ saved
32290 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C15F59A360>: Failed to establish a new connection: [WinError 10065] Сделана попытка выполнить операцию на сокете для недоступного хоста'))
32290 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C15F59B740>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
32290 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C15F5A6CC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
32290 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C15F5A5100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
32290 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C15F5A55E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
32290 ❌ failed after 5 attempts
32293 exception: HTTPSConnectionPool(host='overpass-api.de', port=443): Max retries exceeded with url: /api/interpreter (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C15F5A55E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
32293 error: 504
32293 error: 504
32293 error: 504
32293 ✅ saved
32294 ✅ saved
32295 ✅ saved
32296 ✅ saved
32297 ⚠ 429, sleep 20
32297 error: 504
32297 error: 504
32297 error: 504
32297 error: 504
32297 ❌ failed after 5 attempts
32298 error: 504
32298 error: 504
32298 ✅ saved
32400 error: 504
32400 error: 504
32400 error: 504
32400 ✅ saved
32401 ✅ saved
32402 error: 504
32402 error: 504
32402 ✅ saved
32403 ✅ saved
32404 error: 504
32404 ✅ saved
32405 error: 504
32405 ✅ saved
32406 error: 504
32406 error: 504
32406 ✅ saved
32407 error: 504
32407 error: 504
32407 ✅ saved
32408 ✅ saved
32409 error: 504
32409 ✅ saved
32410 ✅ saved
32411 error: 504
32411 error: 504
32411 error: 504
32411 ✅ saved
32412 error: 504
32412 ✅ saved
32413 error: 504
32413 error: 504
32413 ✅ saved
32414 error: 504
32414 ✅ saved
32415 ✅ saved
32416 ✅ saved
32417 ⚠ 429, sleep 20
32417 ✅ saved
32418 error: 504
32418 error: 504
32418 error: 504
32418 ✅ saved
32419 ✅ saved
32420 error: 504
32420 ✅ saved
32421 ✅ saved
32422 ⚠ 429, sleep 20
32422 error: 504
32422 ✅ saved
32423 ✅ saved
32424 error: 504
32424 ✅ saved
32425 error: 504
32425 error: 504
32425 error: 504
32425 ✅ saved
32426 error: 504
32426 ✅ saved
32600 error: 504
32600 error: 504
32600 ✅ saved
32600 ✅ saved
32600 ✅ saved
32601 error: 504
32601 error: 504
32601 error: 504
32601 error: 504
32601 error: 504
32601 ❌ failed after 5 attempts
32601 ✅ saved
32602 error: 504
32602 error: 504
32602 ✅ saved
32603 error: 504
32603 error: 504
32603 error: 504
32603 ✅ saved
32604 error: 504
32604 error: 504
32604 ✅ saved
32605 error: 504
32605 error: 504
32605 ✅ saved
32606 error: 504
32606 error: 504
32606 error: 504
32606 error: 504
32606 ✅ saved
32607 error: 504
32607 ✅ saved
32608 ✅ saved
32609 error: 504
32609 error: 504
32609 error: 504
32609 ✅ saved
32900 error: 504
32900 ✅ saved
32901 ✅ saved
33200 ✅ saved