In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Задача исследовать файл bike_share/station_list.csv

- читаю файл bike_share/station_list.csv

In [2]:
station_list = pd.read_csv('../../bike_share/station_list.csv')
station_list

     station_id                  station_name
0         30200  9th St & Pennsylvania Ave NW
1         30201                 9th & G St NW
2         31000           Eads St & 15th St S
3         31001           18th St & S Eads St
4         31002        Crystal Dr & 20th St S
..          ...                           ...
911       32901                6035 Warehouse
912       32902          Motivate Tech Office
913       32906     V1 Warehouse Test Station
914       32909              tech trailer V-1
915       33200     17th St & New York Ave NW

[916 rows x 2 columns]

- смотрю уникальные значения

In [5]:
len(station_list['station_id'].unique())

808

- смотрю дубликаты в столбце station_id

In [7]:
station_list[station_list['station_id'].duplicated()]

     station_id                                       station_name
9         31006                          Army Navy Dr & S Joyce St
17        31014                            Lynn St & 19th St North
19        31015                           Wilson Blvd & Ft Myer Dr
32        31027                           Wilson Blvd & N Quinn St
36        31030                         Langston Blvd & N Adams St
..          ...                                                ...
855       32279                      George Mason Blvd & Armstrong
861       32288                         Seatrend Way & Topsails Ln
898       32600                  Founders Row/W Broad St & West St
899       32600  Meridian High School / Haycock Rd & Leesburg Pike
901       32601          State Theatre / Park Pl & N Washington St

[108 rows x 2 columns]

- вывел первые 20 строк у которых есть дубликаты по столбцу station_id

In [14]:
station_list[station_list['station_id'].duplicated(keep=False)].sort_values(by='station_id', ascending=False).head(20)

     station_id                                       station_name
900       32601                                        Eden Center
901       32601          State Theatre / Park Pl & N Washington St
897       32600  George Mason High School / Haycock Rd & Leesbu...
899       32600  Meridian High School / Haycock Rd & Leesburg Pike
898       32600                  Founders Row/W Broad St & West St
860       32288                         Topsails Ln & Seatrend Way
861       32288                         Seatrend Way & Topsails Ln
854       32279                   George Mason Blvd & Armstrong St
855       32279                      George Mason Blvd & Armstrong
845       32270                       Westbranch & Jones Branch Dr
846       32270                    Westbranch Dr & Jones Branch Dr
835       32261    Vaden Dr & Royal Victoria Dr/Jim Scott Cmty Ctr
836       32261  Vaden Dr & Royal Victoria Dr/Providence Commun...
825       32250                        South Gate Community Center
826       32250     Glade Dr & Pinecrest Rd/Cathy Hudgins Cmty Ctr
817       32243                     Reston Town Center Metro North
818       32243                               Fairway Dr & Hook Rd
815       32242                               Inlet Ct & Wiehle Dr
816       32242                          Market St & St Francis St
800       32228              Reston Station Blvd & Sunset Hills Rd

- смотрю разные станции, которые повторяются

In [9]:
station_list[station_list['station_id'] == 31015]

    station_id                              station_name
18       31015  Rosslyn Metro / Wilson Blvd & Ft Myer Dr
19       31015                  Wilson Blvd & Ft Myer Dr

- смотрю есть ли полностью повтояющиеся строчки

In [11]:
station_list[station_list.duplicated()]

Empty DataFrame
Columns: [station_id, station_name]
Index: []

## Вывод
- есть дубликаты их 108 по столбцу (station_id)
- у меня есть еще один файл где уже есть точки станций его нужно посмотреть, что бы точно понять что делать с этими дубликатами
- есть такой шанс что эти станции просто расположены рядом но имеют одинаковый station_id, но название улиц разные